aaa/aaa/urls.py
from django.shortcuts import redirect
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.contrib.auth import views
from django.contrib.auth import authenticate, login
def newlogin(request):
    return redirect('accounts:login')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('archives/', include('archives.urls')),
    path('stats/', include('stats.urls')),
    path('accounts/', include('accounts.urls')),
    path('mcq/', include('mcq.urls')),
    path('notifications/', include('notifications.urls')),
]
if settings.DEBUG:
    urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, {
    'document_root':settings.MEDIA_ROOT
    })
    ]

aaa/archives/urls.py
from django.urls import path
from . import views

app_name = 'archives'


urlpatterns = [
    path('', views.ArchivePage.as_view(), name = 'home_archives'),
    path('lecturepost/<int:pk>', views.LecturePostDetailView.as_view(), name = 'lecture_detail'),
    path('conferencepost/<int:pk>', views.ConferencePostDetailView.as_view(), name = 'conference_detail'),
    path('exfactor', views.LecturePage.as_view(), name = 'lectures'),
    path('lectures', views.LecturePage.as_view(), name = 'lectures'),
    path('send-mail/<int:pk>', views.send_mail_view, name = 'sendmail'),
    path('deletepost-detail/<int:pk>', views.delete_post_detail, name = 'deletepostdetail'),
    path('edit-lecture-detail/<int:pk>/<int:opk>', views.ProfileDetailUpdateView.as_view(), name = 'editdetails'),
    path('edit-lecture-detail/<int:opk>', views.ProfileDetailCreateView.as_view(), name = 'adddetail'),
    path('edit-lecture/<int:pk>', views.LecturePostUpdateView.as_view(), name = 'updatelecture'),
    path('delete-link/<int:pk>', views.PostLinkDeleteView.as_view(), name = 'deletelink'),
    path('edit-links/<int:pk>/<int:opk>', views.PostLinkUpdateView.as_view(), name = 'editlinks'),
    path('create-lecture', views.LecturePostCreateView.as_view(), name = 'createlecture'),
    path('create-conference', views.LecturePostCreateView.as_view(),kwargs={'conference':True}, name = 'createconference'),
    path('details', views.ArchDetail.as_view(), name = 'archdetail'),
    path('testing', views.Test.as_view(), name='test'),
    path('del/<int:pk>', views.delete_book_view, name='deletebook'),
    path('delreview/<int:pk>', views.delete_review_view, name='deletereview')
]

aaa/home/urls.py
from django.urls import path
from . import views
from archives import views as archviews
from .models import Tag


app_name = 'home'

urlpatterns = [
path('posts/<int:pk>', views.PostDetail.as_view(), name = 'postdetail'),
path('users/<str:username>', views.YourPost.as_view(), name = 'yourposts'),
path('getnewposts/<int:pk>', views.GetPosts.as_view(), name = 'getposts'),
path('', views.HomeView.as_view(), name = 'home'),
path('refreshhome', views.refresh_home_page, name = 'refresh'),
path('managewebsite', views.Manage.as_view(), name='manage'),
path('errors', views.StaffError.as_view(), name = 'stafferror'),
path('conferences', archviews.ConferencePage.as_view(), name = 'conf'),
path('searchPage', views.SearchView.as_view(), name = 'search'),
path('editdetails/<int:pk>/<int:detail_pk>', views.PostView.as_view(), name='edittagdetail'),
path('adddetails/<int:pk>', views.PostView.as_view(), name='addtagdetail'),
path('deletetag/<int:pk>/<int:detail_pk>', views.delete_tagdetail_view, name = 'deletetagdetail'),
path('delete_post/<int:pk>', views.delete_post_view, name = 'deletepost'),
path('delete_comment/<int:pk>', views.delete_comment_view, name = 'deletecomment'),
path('commentForm/<int:pk>', views.PostView.as_view(), name = 'commentform'),
path('postform', views.PostView.as_view(), name = 'postview'),
path('create_post', views.create_post_view, name='postForm'),
path('home/<str:speciality_type>', views.speciality_view, name = 'speciality')
]

aaa/archives/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView, DetailView
from .models import *
from home.decorators import staff_required, log_required
from accounts.models import User, Profile, ProfileDetail
from home.models import  Tag, PostLink
from .forms import *
import bleach, datetime,pytz
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from .models import LecturePost
from accounts.models import ProfileDetail
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.
class LecturePostDetailView(DetailView):
    model = LecturePost
    template_name = 'archives/lecture_detail.html'
    context_object_name = 'post'
    extra_context = {'lecture':True}
class ConferencePostDetailView(DetailView):
    model = LecturePost
    template_name = 'archives/lecture_detail.html'
    context_object_name = 'post'
    extra_context = {'lecture':False}


class LecturePage(TemplateView):
    template_name = 'archives/hello.html'

    @method_decorator(log_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        utc = pytz.UTC
        tz = pytz.timezone('Asia/Kolkata')
        today = datetime.datetime.now(tz)
        x = []
        y = []
        for i in LecturePost.objects.filter(lecture=True).order_by('-pk'):
            if utc.localize(i.lecture_start_date) > today:
                x.append(i)
            else:
                y.append(i)
        context['lectures'] = x
        context['pastlectures'] = y
        tag_speciality = Tag.objects.filter(is_speciality=True)
        context['tag_speciality'] = list(tag_speciality)
        print(context)
        return context

class ConferencePage(TemplateView):
    template_name = 'home/conference.html'
    @method_decorator(log_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = Tag.objects.get(name='Conferences')
        context['oldposts'] = Post.objects.filter(tag=tag, conference=False).order_by('-pk')
        tag_speciality = Tag.objects.filter(is_speciality=True)
        context['tag_speciality'] = list(tag_speciality)
        context['posts'] = LecturePost.objects.filter(tag=tag, conference=True).order_by('lecture_start_date')
        return context

class LecturePostCreateView(CreateView):
    model = LecturePost
    form_class = LecturePostForm
    success_url = '/'
    @method_decorator(staff_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    def get_template_names(self):
        if self.request.GET.get('createconference'):
            template_name = 'home/conferenceForm.html'
        else:
            template_name = 'home/lectureform.html'
        return template_name

    def get(self, request, *args, **kwargs):
        if not request.GET.get('createconference'):
            self.kwargs['conference'] = None
        return super().get(request, *args, **kwargs)
    def post(self, *args, **kwargs):
        if self.request.POST.get('conferencebtn'):
            self.kwargs['conference'] = True
        else:
            self.kwargs['conference'] = False
        return super().post(self.request, *args, **kwargs)
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(request=self.request)
        kwargs.update(self.kwargs)
        return kwargs
    def get_success_url(self):
        if self.kwargs['conference']:
            return reverse('home:conf')
        return reverse('archives:lectures')
class ProfileDetailUpdateView(UpdateView):
    model = ProfileDetail
    form_class = ProfileDetailForm
    success_url = '/'
    template_name = 'home/profiledetailsform.html'
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(request=self.request)
        kwargs.update(self.kwargs)
        kwargs.update(obj = LecturePost.objects.get(pk=kwargs['opk']))
        return kwargs
    def get_success_url(self):
        return reverse('archives:lectures')
class ProfileDetailCreateView(CreateView):
    model = ProfileDetail
    form_class = ProfileDetailForm
    success_url = '/'
    template_name = 'home/profiledetailsform.html'
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(request=self.request)
        kwargs.update(self.kwargs)
        kwargs.update(obj = LecturePost.objects.get(pk=kwargs['opk']))
        return kwargs
    def get_success_url(self):
        return reverse('archives:lectures')

class LecturePostUpdateView(UpdateView):
    model = LecturePost
    form_class = LecturePostForm
    success_url = '/'

    @method_decorator(staff_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_template_names(self):
        if self.request.GET.get('createconference'):
            template_name = 'home/conferenceForm.html'
        else:
            template_name = 'home/lectureform.html'
        return template_name
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(request=self.request)
        kwargs.update(self.kwargs)
        return kwargs
    def get_success_url(self):
        return reverse('archives:lectures')




class PostLinkUpdateView(UpdateView):
    model = PostLink
    template_name = 'home/linkform.html'
    form_class = PostLinkForm
    success_url = '/'
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(request=self.request)
        kwargs.update(self.kwargs)
        kwargs.update(obj = LecturePost.objects.get(pk=kwargs['opk']))
        return kwargs
    def get_success_url(self):
        return reverse('archives:lectures')
class PostLinkDeleteView(DeleteView):
    model = PostLink
    template_name = None

class ArchivePage(TemplateView):
    template_name = 'home/archie.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_staff:
            return render(request, self.template_name, self.get_context_data())
        else:
            return redirect('home:stafferror')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag_speciality'] = Tag.objects.filter(is_speciality=True)
        return context

class CleanLinkMixin:
    def assign_links(self):
        link_name = self.request.POST.getlist('link_name')
        link = self.request.POST.getlist('link')
        if len(link_name) != len(link) or len(link_name)==0:
            return False
        else:
            return list(zip(link_name, link))

    def clean_links(self, **kwargs):
        newdic = {}
        newdic['links'] = []
        if self.assign_links():
            for i in self.assign_links():
                if i:
                    validator = URLValidator()
                    link_name = bleach.clean(i[0], strip=True)
                    try:
                        validator(i[1])
                        link = i[1]
                        newdic['links'].append([link_name, link])

                    except ValidationError:
                        print('url not valid')
                        messages.error(self.request, 'Kindly enter valid Url ')
                        return False
            objlist = self.create_links(newdic)
            if objlist:
                return objlist
            else:
                return False

        else:
            return False
    def create_links(self, newdic):
        objlist =[]
        if newdic:
            print(newdic)
            for key in newdic:
                if key and newdic[key]:
                    for linkobj in newdic[key]:
                        print(linkobj)
                        try:
                            a = PostLink.objects.get(link_name = linkobj[0], link=linkobj[1])
                            objlist.append(a)
                            print('link obj already presetn')
                        except:
                            a = PostLink.objects.create(link_name = linkobj[0], link=linkobj[1])
                            a.user = self.request.user
                            a.save()
                            print('link object created')
                            objlist.append(a)
                    return objlist
                else:
                    return False


        else:
            return False


class CleanTextMixin:
    def clean_text(self, a):
        newdic = {}
        if a:
            print(a)
            for i in a:

                tagtext = bleach.clean(self.request.POST.get(i), strip=True)
                if i == 'subjecttag':
                    try:
                        x = Tag.objects.get(name=tagtext, is_degree=True)
                        newdic[i] = x
                    except:
                        messages.error(self.request, 'Kindly enter valid tag ')
                        return False

                else:
                    newdic[i] = tagtext


            return newdic

        else:
            messages.error(self.request, 'Kindly enter text ')
            return False

class CleanImageMixin:

    def image_valid(self, *args):
        valid_extensions = ['jpeg', 'png', 'jpg']
        if args:
            for i in args:
                if not i:
                    return False
                print(i.name.split('.'))

aaa/archives/templates/archives/arch.html
{% extends "home/base.html" %}
{% load static %}
{% block main %}
<style media="screen">
.lecture{
  display: flex;
  flex-flow: column wrap;
  border-top: 4px inset dimgrey;
  justify-content: center;
}

</style>
<div class="home-container">
<div class="upcoming flex-column">

<h2 style="align-self: center">Upcoming Lectures</h2>
{% if request.user.is_admin %}
<b class="center"><a href="{% url 'archives:createlecture' %}"> Create Lecture</a></b>
{% endif %}

{% if messages.extra_tags == request.user.email %}
<p class="bold-green">{{ messages }}</p>

{% endif %}
{% for post in lectures %}
<div class="home-post lecture">
  <h2 style="color: #800000"> {{ post.get_lecture_range }}</h2>
  <div class="regulartags tags">
    {% for tag in post.get_tags %}
    {% if tag.is_degree %}
    <p class="degree"><a style="margin:5px;text-decoration:none;color: white;" href="{% url 'home:speciality' tag.name %}">{{tag.name}}</a></p>
    {% else %}
    <p style="text-decoration:none; font-weight: 400;margin-right: 10px;text-align: center;" ><a id = '{{tag.name}}' style="margin: 5px;text-decoration: none" href="{% url 'home:speciality' tag.name %}">{{tag.name}}</a>  </p>

    {% endif %}
    {% endfor %}
  </div>
  <div class="home-post-heading">
      <h3>{{post.heading | linebreaks }}</h3>
      <div class="socialmediatags tags">

        <a href="whatsapp://send?text={{ post.get_absolute_url }}"><img src="{% static 'home/images/whatsapp.png' %}" height=20px, width=20px alt=""> </a>
 <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={{ post.get_absolute_url }}" ><img src="{% static 'home/images/facebook.png' %}" height=20px, width=20px alt=""></a>
 {% if request.user.is_admin and request.user == post.user  or request.user.email == 'suryaveda@hotmail.com' %}
 <a href="#">edit</a>
 <a class="bold-red" href="{% url 'archives:updatelecture' post.pk %}"><img src="{% static 'home/images/edit.png' %}" height="20px" width="20px" alt=""></a>

 {% endif %}

      </div>

      {% if request.user.is_authenticated and request.user == post.user or request.user.is_admin%}
     <form onsubmit="deleteposte(event, {{post.pk}})" method="post" enctype="application/x-www-form-urlencoded">
     {% csrf_token %}
      <input type="submit" name = 'deletepostbtn{{post.pk}}' value="Delete Lecture" style="text-decoration: underline; color: #000066" >
     </form>
     {%endif %}
     <p style="color: #000066"><b>{{post.posted_on}} </b></p>


  </div>

 {% if post.img %}
 <div class="home-post-img">
     <img  src="/media/{{post.img}}" width="250px" height="250px">
 </div>

 {% endif  %}
 {% if request.user.is_admin and request.user == post.user %}
 <p><a href="{% url 'archives:adddetail' post.pk %}"><img src="{% static 'home/images/details.png' %}" height="30px" width="30px" alt=""></a></p>

 {% endif %}
 {% if post.get_post_details %}
 {% for i in post.get_post_details %}
 <div class="showsubjectintro">

 <h2 style="text-decoration: underline; font-weight: 600; color: #000066;">{{i.heading}}
   {% if request.user.is_admin %}
   <a href="{% url 'archives:editdetails' i.pk post.pk%}"> <img src="{% static 'home/images/edit.png' %}" height="20px" width="20px" alt=""> </a><a style="margin-left: 10px" href="{% url 'archives:deletepostdetail' i.pk %}"><img src="{% static 'home/images/delete.png' %}" height="20px" width="20px"></a>

   {% endif %}
 </h2>

     {% if i.details %}
     <p>{{i.details|linebreaks }}</p>
     {% else %}
     {% endif %}
 </div>
 {% endfor %}
 {% endif %}



 {% if post.get_links %}
 <h3>Attached Links</h3>
 <p>testing</p>
 <form class="" action="{% url 'archives:sendmail' post.pk %}" method="post">
   {% csrf_token %}
   <button style="height: 50px;width: 80px;background-color: #000066;color:white;" type="submit" name="button"> Get Zoom link to your mail</button>
 </form>
 {% endif  %}

 {% if post.pdf %}
 <b>Attached Pdfs</b>
 <div class="home-post-pdf">
     <a href="{{post.pdf}}"><p>{{post.pdf_name}}: {{post.pdf}}</p></a>
 </div>
 {% endif  %}
 <div id="comments{{post.pk}}" class="comments ">
     <h2 style="text-decoration: underline">Comments</h2>
 {% if post.get_comments %}
 <div class="home-post-comments">
 {% for comment in post.get_comments %}
     <div class="home-post-comment-single">
         <p style="font-size: 14px;text-decoration:underline;color: #000066"><b>{{comment.user.username}} | {{comment.posted_on}}</b></p>
{% if request.user.is_staff and request.user == comment.user%}
<p style="text-decoration: underline; color: #000066" ><a onclick="deletecomment(event, {{comment.pk}})">Delete Comment.</a></p>
{%endif %}

   {% if comment.img %}

 <div  class="home-post-img">
     <img  src="/media/{{comment.img}}" width="250px" height="250px">
 </div>

 {% endif  %}



 {% if comment.text %}
 <div class="home-post-content">
     <p>{{comment.text|linebreaks }}</p>
 </div>
 {% endif  %}




 {% if comment.get_links %}
         <b>Attached links</b>
 {% for i in comment.get_links %}
 <div class="home-post-link">
     <a href="{{i.link}}"><p>{{i.link_name}}: {{i.link}}</p></a>
 </div>
 {%endfor%}
 {% endif  %}
 {% if comment.pdf %}
         <b>Attached pdfs</b>
 <div class="home-post-pdf">
     <a href="{{comment.pdf}}"><p>{{comment.pdf_name}}: {{comment.pdf}}</p></a>
 </div>
 {% endif  %}
         </div>
 {% endfor %}
 </div>
 {% endif  %}
 <div class="comment-create-form">
  <form enctype="multipart/form-data" method="post" action="{% url 'home:commentform' post.pk %}">
         {% csrf_token %}
     <p>Add image: <input type="file" name="image" ></p>
<br>
     <p><textarea required type="text" name="text" placeholder="Enter Comment.."></textarea></p>
<br>
     <p><input name="pdf_name" type="text" placeholder="Add pdf name" maxlength="20" value="">: <input type="file" name="pdf"></p>
      <div id="addlinkform{{post.pk}}">
          <p><input type="text"  placeholder="Add link name.." maxlength="20" name="link_name" value="">: <input type="url" placeholder="Add link url.." value="" maxlength="200"  name="link"></p>
      </div>
      <p style="text-decoration: underline;color: #000066;"><a onclick="addnewlinkforms('addlinkform{{post.pk}}')"> Add more links</a></p>
     <button name="createcomment" type="submit" value="createcomment">Submit</button>
     </form>

     </div>

 </div>
            <p onclick="expand(this, 'comments{{post.pk}}')" style="color: red; text-decoration: underline;" class="more">See Comments</p>

 </div>
{% endfor %}
</div>




<div class="pastlectures flex-column">
<h2 class="center">Past Lectures</h2>
{% for post in pastlectures %}
<div class="home-post lecture">
  <h2 style="color: #800000"> {{ post.get_lecture_range }}</h2>
  <div class="regulartags tags">
    {% for tag in post.get_tags %}
    {% if tag.is_degree %}
    <p class="degree"><a style="margin:5px;text-decoration:none;color: white;" href="{% url 'home:speciality' tag.name %}">{{tag.name}}</a></p>
    {% else %}
    <p style="text-decoration:none; font-weight: 400;margin-right: 10px;text-align: center;" ><a id = '{{tag.name}}' style="margin: 5px;text-decoration: none" href="{% url 'home:speciality' tag.name %}">{{tag.name}}</a>  </p>

    {% endif %}
    {% endfor %}
  </div>
  <div class="home-post-heading">
      <h3>{{post.heading | linebreaks }}</h3>
      <div class="socialmediatags tags">

        <a href="whatsapp://send?text={{ post.get_absolute_url }}"><img src="{% static 'home/images/whatsapp.png' %}" height=20px, width=20px alt=""> </a>
 <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={{ post.get_absolute_url }}" ><img src="{% static 'home/images/facebook.png' %}" height=20px, width=20px alt=""></a>
 {% if request.user.is_admin and request.user == post.user %}
 <a class="bold-red" href="{% url 'archives:updatelecture' post.pk %}"><img src="{% static 'home/images/edit.png' %}" height="20px" width="20px" alt=""></a>

 {% endif %}

      </div>

      {% if request.user.is_authenticated and request.user == post.user or request.user.is_admin%}
     <form onsubmit="deleteposte(event, {{post.pk}})" method="post" enctype="application/x-www-form-urlencoded">
     {% csrf_token %}
      <input type="submit" name = 'deletepostbtn{{post.pk}}' value="Delete Lecture" style="text-decoration: underline; color: #000066" >
     </form>
     {%endif %}
     <p style="color: #000066"><b>{{post.posted_on}} </b></p>


  </div>

 {% if post.img %}
 <div class="home-post-img">
     <img  src="/media/{{post.img}}" width="250px" height="250px">
 </div>

 {% endif  %}
 {% if request.user.is_admin and request.user == post.user %}
 <p><a href="{% url 'archives:adddetail' post.pk %}"><img src="{% static 'home/images/details.png' %}" height="30px" width="30px" alt=""></a></p>

 {% endif %}
 {% if post.get_post_details %}
 {% for i in post.get_post_details %}
 <div class="showsubjectintro">

 <h2 style="text-decoration: underline; font-weight: 600; color: #000066;">{{i.heading}}
   {% if request.user.is_admin %}
   <a href="{% url 'archives:editdetails' i.pk post.pk%}"> <img src="{% static 'home/images/edit.png' %}" height="20px" width="20px" alt=""> </a><a style="margin-left: 10px" href="{% url 'archives:deletepostdetail' i.pk %}"><img src="{% static 'home/images/delete.png' %}" height="20px" width="20px"></a>

   {% endif %}
 </h2>

     {% if i.details %}
     <p>{{i.details|linebreaks }}</p>
     {% else %}
     {% endif %}
 </div>
 {% endfor %}
 {% endif %}


 {% if post.get_links %}
 <h3>Attached Links</h3>
 <div class="home-post-link">

 {% for i in post.get_links %}


<p><b>{{i.link_name}}</b>: <a href="{{ i.link }}">{{ i.link }}</a>   {% if request.user.is_admin %}
<a class="bold-red" style="margin-left: 10px;" href="{% url 'archives:editlinks' i.pk post.pk %}"><img src="{% static 'home/images/edit.png' %}" height="20px" width="20px" alt=""></a>

{% endif %}</p>

 {%endfor%}
  </div>
 {% endif  %}

 {% if post.pdf %}
 <b>Attached Pdfs</b>
 <div class="home-post-pdf">
     <a href="{{post.pdf}}"><p>{{post.pdf_name}}: {{post.pdf}}</p></a>
 </div>
 {% endif  %}
 <div id="comments{{post.pk}}" class="comments ">
     <h2 style="text-decoration: underline">Comments</h2>
 {% if post.get_comments %}
 <div class="home-post-comments">
 {% for comment in post.get_comments %}
     <div class="home-post-comment-single">
         <p style="font-size: 14px;text-decoration:underline;color: #000066"><b>{{comment.user.username}} | {{comment.posted_on}}</b></p>
{% if request.user.is_staff and request.user == comment.user%}
<p style="text-decoration: underline; color: #000066" ><a onclick="deletecomment(event, {{comment.pk}})">Delete Comment.</a></p>
{%endif %}

   {% if comment.img %}

 <div  class="home-post-img">
     <img  src="/media/{{comment.img}}" width="250px" height="250px">
 </div>

 {% endif  %}



 {% if comment.text %}
 <div class="home-post-content">
     <p>{{comment.text|linebreaks }}</p>
 </div>
 {% endif  %}




 {% if comment.get_links %}
         <b>Attached links</b>
 {% for i in comment.get_links %}
 <div class="home-post-link">
     <a href="{{i.link}}"><p>{{i.link_name}}: {{i.link}}</p></a>
 </div>
 {%endfor%}
 {% endif  %}
 {% if comment.pdf %}
         <b>Attached pdfs</b>
 <div class="home-post-pdf">
     <a href="{{comment.pdf}}"><p>{{comment.pdf_name}}: {{comment.pdf}}</p></a>
 </div>
 {% endif  %}
         </div>
 {% endfor %}
 </div>
 {% endif  %}
 <div class="comment-create-form">
  <form enctype="multipart/form-data" method="post" action="{% url 'home:commentform' post.pk %}">
         {% csrf_token %}
     <p>Add image: <input type="file" name="image" ></p>
<br>
     <p><textarea required type="text" name="text" placeholder="Enter Comment.."></textarea></p>
<br>
     <p><input name="pdf_name" type="text" placeholder="Add pdf name" maxlength="20" value="">: <input type="file" name="pdf"></p>
      <div id="addlinkform{{post.pk}}">
          <p><input type="text"  placeholder="Add link name.." maxlength="20" name="link_name" value="">: <input type="url" placeholder="Add link url.." value="" maxlength="200"  name="link"></p>
      </div>
      <p style="text-decoration: underline;color: #000066;"><a onclick="addnewlinkforms('addlinkform{{post.pk}}')"> Add more links</a></p>
     <button name="createcomment" type="submit" value="createcomment">Submit</button>
     </form>

     </div>

 </div>
            <p onclick="expand(this, 'comments{{post.pk}}')" style="color: red; text-decoration: underline;" class="more">See Comments</p>

 </div>
{% endfor %}
</div>
</div>
{% endblock %}

aaa/archives/templates/archives/hello.html
{% extends "home/base.html" %}
{% load static %}
{% block main %}
<style media="screen">
.lecture{
  display: flex;
  flex-flow: column wrap;
  border-top: 4px inset dimgrey;
  justify-content: center;
}

</style>
<div class="home-container">
<div class="upcoming flex-column">

<h2 style="align-self: center">Upcoming Lectures</h2>
{% if request.user.is_admin %}
<b class="center"><a href="{% url 'archives:createlecture' %}"> Create Lecture</a></b>
{% endif %}

{% if lectures %}
{% for post in lectures %}
{% include "home/basetemplates/lecturebase.html" %}
{% endfor %}
{% else %}
<p class="bold-red center" style="margin:30px;"> No upcoming lectures.</p>
{% endif %}

</div>

<div class="pastlectures flex-column">
<h2 class="center">Past Lectures</h2>
{% for post in pastlectures %}
{% include "home/basetemplates/lecturebase.html" %}
{% endfor %}
</div>
</div>
{% endblock %}

aaa/archives/templates/archives/lecture_detail.html
{% extends "home/base.html" %}
{% load static %}
{% block main %}

{% if lecture %}
{% include "home/basetemplates/lecturebase.html" %}


{% else %}
{% include "home/basetemplates/conferencebase.html" %}
{% endif %}


{% endblock %}