aaa/aaa/urls.py
from django.shortcuts import redirect
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.contrib.auth import views
from django.contrib.auth import authenticate, login
def newlogin(request):
    return redirect('accounts:login')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('archives/', include('archives.urls')),
    path('stats/', include('stats.urls')),
    path('accounts/', include('accounts.urls')),
    path('mcq/', include('mcq.urls')),
    path('notifications/', include('notifications.urls')),
]
if settings.DEBUG:
    urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, {
    'document_root':settings.MEDIA_ROOT
    })
    ]

aaa/archives/urls.py
from django.urls import path
from . import views

app_name = 'archives'


urlpatterns = [
    path('', views.ArchivePage.as_view(), name = 'home_archives'),
    path('lecturepost/<int:pk>', views.LecturePostDetailView.as_view(), name = 'lecture_detail'),
    path('conferencepost/<int:pk>', views.ConferencePostDetailView.as_view(), name = 'conference_detail'),
    path('exfactor', views.LecturePage.as_view(), name = 'lectures'),
    path('lectures', views.LecturePage.as_view(), name = 'lectures'),
    path('send-mail/<int:pk>', views.send_mail_view, name = 'sendmail'),
    path('deletepost-detail/<int:pk>', views.delete_post_detail, name = 'deletepostdetail'),
    path('edit-lecture-detail/<int:pk>/<int:opk>', views.ProfileDetailUpdateView.as_view(), name = 'editdetails'),
    path('edit-lecture-detail/<int:opk>', views.ProfileDetailCreateView.as_view(), name = 'adddetail'),
    path('edit-lecture/<int:pk>', views.LecturePostUpdateView.as_view(), name = 'updatelecture'),
    path('delete-link/<int:pk>', views.PostLinkDeleteView.as_view(), name = 'deletelink'),
    path('edit-links/<int:pk>/<int:opk>', views.PostLinkUpdateView.as_view(), name = 'editlinks'),
    path('create-lecture', views.LecturePostCreateView.as_view(), name = 'createlecture'),
    path('create-conference', views.LecturePostCreateView.as_view(),kwargs={'conference':True}, name = 'createconference'),
    path('details', views.ArchDetail.as_view(), name = 'archdetail'),
    path('testing', views.Test.as_view(), name='test'),
    path('del/<int:pk>', views.delete_book_view, name='deletebook'),
    path('delreview/<int:pk>', views.delete_review_view, name='deletereview')
]

aaa/home/urls.py
from django.urls import path
from . import views
from archives import views as archviews
from .models import Tag


app_name = 'home'

urlpatterns = [
path('posts/<int:pk>', views.PostDetail.as_view(), name = 'postdetail'),
path('users/<str:username>', views.YourPost.as_view(), name = 'yourposts'),
path('getnewposts/<int:pk>', views.GetPosts.as_view(), name = 'getposts'),
path('', views.HomeView.as_view(), name = 'home'),
path('refreshhome', views.refresh_home_page, name = 'refresh'),
path('managewebsite', views.Manage.as_view(), name='manage'),
path('errors', views.StaffError.as_view(), name = 'stafferror'),
path('conferences', archviews.ConferencePage.as_view(), name = 'conf'),
path('searchPage', views.SearchView.as_view(), name = 'search'),
path('editdetails/<int:pk>/<int:detail_pk>', views.PostView.as_view(), name='edittagdetail'),
path('adddetails/<int:pk>', views.PostView.as_view(), name='addtagdetail'),
path('deletetag/<int:pk>/<int:detail_pk>', views.delete_tagdetail_view, name = 'deletetagdetail'),
path('delete_post/<int:pk>', views.delete_post_view, name = 'deletepost'),
path('delete_comment/<int:pk>', views.delete_comment_view, name = 'deletecomment'),
path('commentForm/<int:pk>', views.PostView.as_view(), name = 'commentform'),
path('postform', views.PostView.as_view(), name = 'postview'),
path('create_post', views.create_post_view, name='postForm'),
path('home/<str:speciality_type>', views.speciality_view, name = 'speciality')
]

aaa/mcq/urls.py
from django.urls import path
from . import views
app_name = 'mcq'

urlpatterns = [

path('', views.McqView.as_view(), name = 'qa'),
path('<str:pk>', views.McqView.as_view(), name='subjectquestions'),
path('refreshquestions', views.refresh_questions_view, name='refreshq'),
path('createquestions/<str:type>', views.CreateQuestion.as_view(), name='createq'),
path('getnewquestions/<str:index>', views.GetQuestions.as_view(), name='getq'),
path('deletequestions/<int:pk>', views.delete_question_view, name = 'deleteq'),
path('question/<int:qpk>', views.QuestionDetail.as_view(), name = 'qdetail'),
]

aaa/home/forms.py
from django.forms import ModelForm
from django import forms
from .models import Post, Tag, Comment


class Custommmf(forms.ModelMultipleChoiceField):
    def label_from_instance(self, tag):
        return  '%s' % tag.name

class CreatePostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['tag','heading', 'img', 'content', 'pdf_name', 'pdf']

    tag = Custommmf(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )
    
    def __init__(self, *args, **kwargs):
        super(CreatePostForm, self).__init__(*args, **kwargs)
        self.fields['heading'].widget.attrs['placeholder'] = 'Post heading/Question/title'
        self.fields['tag'].required = True
        self.fields['pdf_name'].widget.attrs['placeholder'] = 'name of pdf'
        self.fields['content'].widget = forms.Textarea(attrs={'rows': 4, 'cols': 15})
        self.fields['content'].widget.attrs['placeholder'] = 'Content of post/mcq/answer'

aaa/home/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Post,Comment, Tag, PostLink
from notifications.mixins import CreateNotificationMixin
from archives.models import Book, LecturePost
from django.utils.decorators import method_decorator
from accounts.models import User, ProfileDetail
from home.mixins import ValidateLinkMixin, ValidateTextMixin, ValidateFileMixin, GeneralContextMixin
from .forms import CreatePostForm
from .decorators import staff_required, admin_required
from django.utils import timezone
from django.contrib import messages
from django.views.generic import TemplateView
import bleach, datetime,pytz
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from  django.core.mail import send_mail
from django.core.exceptions import ObjectDoesNotExist
from django.views import View
from mcq.models import QuestionBank
from notifications.models import Notification, Message
from archives.models import LecturePost
from fb.mixins import PublishInFacebook
# Create your views here.
class Manage(TemplateView):
    template_name = 'home/manage.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data( **kwargs)
        if self.request.user.is_staff:
            context['users'] = User.objects.order_by('-pk')
            context['users_length'] = len(context['users'])
            tag_speciality = Tag.objects.filter(is_speciality=True)
            context['tag_speciality'] = list(tag_speciality)

        return context
def email(request):
    subject = 'You visited conference page'
    message = ' it  means a world to us '
    email_from = settings.EMAIL_HOST_USER
    recipient_list = ['suryaveda@hotmail.com',]
    send_mail( subject, message, email_from, recipient_list )
    return redirect('home:home')

class HomeView(PublishInFacebook,TemplateView):
    template_name = 'home/home.html'
    posts = []
    postslist = []

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        questionbank = QuestionBank.objects.all()
        context['questionbank'] = list(questionbank.filter(mcq=True))
        context['flashcards'] = list(questionbank.filter(flashcard=True))
        postslist = list(Post.objects.filter(lecture=False, conference=False).order_by('-date').prefetch_related())


        print(len(postslist))
        utc = pytz.UTC
        tz = pytz.timezone('Asia/Kolkata')
        today = datetime.datetime.now(tz)
        context['lectures'] = [i for i in LecturePost.objects.filter(lecture=True).order_by('-pk') if utc.localize(i.lecture_start_date) > today]
        context['conferences'] = [i for i in LecturePost.objects.filter(lecture=False).order_by('lecture_start_date') if utc.localize(i.lecture_start_date) > today]
        context['posts'] = postslist[0:15]

        tag_speciality = Tag.objects.filter(is_speciality=True)
        context['tag_speciality'] = list(tag_speciality)
        return context

def refresh_home_page(request):
    HomeView.tag_speciality  = Tag.objects.filter(is_speciality=True)
    print(HomeView.posts)
    HomeView.postslist.clear()
    HomeView.postslist = list(Post.objects.order_by('-date').prefetch_related())
    return redirect('home:home')


class StaffError(TemplateView):
    template_name = 'home/stafferror.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['tag_speciality'] = Tag.objects.filter(is_speciality=True)
        return context


def show_conferences(request):
    a= Tag.objects.get(name = 'Conferences')
    posts = a.post_set.all().order_by('-pk')
    tag_speciality = Tag.objects.filter(is_speciality=True)
    return render(request, 'home/conference.html', {'posts':posts,'tag_speciality': tag_speciality})

def speciality_view(request, speciality_type):

    if request.user:
        template_name = 'home/speciality_tag.html'
        context = {}
        try:
            tag = Tag.objects.get(name=speciality_type)

            if speciality_type=='NEET-SS':
                questionbank = QuestionBank.objects.all()
                template_name = 'home/neet.html'
                context['questionbank'] = list(questionbank.filter(mcq=True))
                context['flashcards'] = list(questionbank.filter(flashcard=True))
                context['cases'] = list(questionbank.filter(qa=True))


            subjects = list(Tag.objects.filter(is_degree=True))

            posts = Post.objects.filter(tag=tag, lecture=False).order_by('-pk')
            tag_speciality = Tag.objects.filter(is_speciality=True)
            context['tag'] = tag
            context['tag_speciality'] = tag_speciality
            context['posts'] = posts
            context['subjects'] = subjects
            return render(request, template_name, context)
        except:
            messages.error(request, 'unable to fetch the page.')
            return redirect('home:home')

    else:
        return redirect('accounts:login')



class SearchView(TemplateView):

    template_name = 'home/search.html'

    def get(self, request, *args, **kwargs):

        if request.user:
            return render(request, self.template_name, self.get_context_data())
        else:
            return redirect('accounts:login')
    def get_posts(self):
        searchInput = self.request.GET.get('searchinput')
        if not searchInput:
            messages.error(self.request, 'Enter something in search!')
            return False
        query = bleach.clean(searchInput, strip=True)
        posts = Post.objects.filter(heading__icontains = query, lecture=False)
        return list(posts)

    def get_books(self):
        searchInput = self.request.GET.get('searchinput')
        if not searchInput:
            messages.error(self.request, 'Enter something in search!')
            return False
        query = bleach.clean(searchInput, strip=True)
        books = Book.objects.filter(name__icontains=query)
        return list(books)
    def get_lectures(self):
        searchInput = self.request.GET.get('searchinput')
        if not searchInput:
            messages.error(self.request, 'Enter something in search!')
            return False
        query = bleach.clean(searchInput, strip=True)
        books = LecturePost.objects.filter(heading__icontains=query)
        return list(books)

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['tag_speciality'] = Tag.objects.filter(is_speciality=True)
        searchInput = self.request.GET.get('searchinput')
        if not searchInput:
            context['someresults'] = True
            return context
        context['posts'] = self.get_posts()

        context['lectures'] = self.get_lectures()
        if self.request.user.is_staff:
            context['books'] = self.get_books()
        else:
            context['books'] = False

        if context['posts'] and context['books'] and context['lectures']:
            context['someresults'] = True
        else:
            context['someresults'] = False
        return context



def delete_post_view(request,pk):
    ex= redirect('home:home')
    if pk and request.user.is_authenticated:

        try:
            x = Post.objects.get(pk = pk)
            if x.user == request.user or request.user.is_admin:
                print(x.get_absolute_url())
                Message.objects.delete_messages(x.get_absolute_url())
                x.delete()
                ex = refresh_home_page(request)
                print(ex.url)
                print(ex.status_code)
                return JsonResponse({'success': ex.url}, safe=False)
            else:
                messages.error(request, 'not a valid user')
                return JsonResponse({'success': ex.url}, safe=False)


        except:
            messages.error(request, 'post is not present in database')
            return JsonResponse({'success': ex.url}, safe=False)
    else:
        messages.error(request, 'select valid post')

        return JsonResponse({'success': ex.url}, safe=False)


def delete_comment_view(request,pk):
    ex= redirect('home:home')
    if pk and request.user.is_authenticated:
        try:
            x = Comment.objects.get(pk = pk)
            if x.user == request.user or request.user.is_admin:
                x.delete()
                ex = refresh_home_page(request)
                print(ex.url)
                return JsonResponse({'success': ex.url}, safe=False)
            else:
                messages.error(request, 'not a valid user')
                return JsonResponse({'success': ex.url}, safe=False)
        except:
            messages.error(request, 'post is not present in database')
            return JsonResponse({'success': ex.url}, safe=False)
    else:
        messages.error(request, 'select valid post')

        return JsonResponse({'success': ex.url}, safe=False)


def delete_tagdetail_view(request,pk,detail_pk):
    if pk and request.user.is_authenticated and request.user.is_admin:

        try:
            print(type(pk))
            y = Tag.objects.get(pk = pk)
            x = y.get_details
            print(x)
            for i in x:
                if i.pk == detail_pk :
                    print(i)
                    i.delete()
                else:
                    messages.error(request, 'not a valid user')

            return redirect('/home/{0}'.format(y.name))
        except:
            print('some problem')
            messages.error(request, 'post is not present in database')
            return redirect('home:home')
    else:
        messages.error(request, 'select valid post')

        return redirect('home:home')
@staff_required
def create_post_view(request):
    if request.user and request.user:
        print('hello')
        template_name = 'home/home_post.html'
        form = CreatePostForm()

aaa/home/templates/home/basetemplates/add_subject_details.html
{% load static %}
<form style="display: none;" id = 'subject-intro-edit' method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p><input placeholder="Add heading.." style="border-radius: 4px;  height: 35px;  font-size: 14px;  font-family: 'Overlock', cursive;" required name="heading" type="text" maxlength="50" value="{{i.heading}}"></p> <br>
        <p><textarea   required name="details" type="text" maxlength="5000" >{{i.details}} </textarea></p>

        <button style="border-radius: 4px;  width:65px;  height:40px;  background-color: #000066; color: white;" name="edittagdetail" type="submit" value="profdetails">Submit</button>
    </form>
<form style="display: none;" action="{% url 'home:addtagdetail' tag.pk %}" method="post" id="subject-intro-add" enctype="application/x-www-form-urlencoded">
     {% csrf_token %}

      <p><input placeholder="Add heading..." style="border-radius: 4px;  height: 35px;  font-size: 14px;  font-family: 'Overlock', cursive;" required name="heading" type="text" maxlength="50" value=""></p> <br>
        <p><textarea placeholder="Add details..." required name="details" type="text" maxlength="5000" > </textarea></p>

        <button style="border-radius: 4px;  width:65px;  height:40px;  background-color: #000066; color: white;" name="addtagdetail" type="submit" value="profdetails">Submit</button>

 </form>

aaa/home/templates/home/basetemplates/books.html
{% load static %}
{% load custom_tags %}

<div class="book-form" style="margin: 40px 0;border-bottom: 5px solid black;">
    <div class="book-cover-form">
    <div class="book-poster">
        {% if request.user.is_authenticated and request.user.is_admin and request.user == book.user %}
    <script>var deleteurl{{book.pk}} = '{% url "archives:deletebook" book.pk %}'</script>
    <p><a style="text-decoration: underline; color: #000066" onclick="removebook(deleteurl{{book.pk}})">Remove the book </a></p>
    {% endif %}
        {% if book.backgroundPic %}
        <img src="/media/{{book.backgroundPic}}" width="180px" height="180px">
        {% else %}
        <img src="{% static 'home/images/defaultbackgroundimage.jpg' %}" width="180px" height="180px">

        {% endif %}
        {% if book.get_source_link %}
        {% for i in book.get_source_link %}

        <p><a href="{{i.1}}" > GET</a></p>
        {%endfor %}

       {% endif %}
    </div>
    <div class="book-review-form">
        {% if book.name %}
       <p> Name: {{book.name}}</p>
      {% endif %}

        {% if book.latest %}
       <p> Last Edition: {{book.latest}}</p>
        {% endif %}

    </div>
        </div>
    <div class="book-content-form">
        <h4>Review</h4>

           {% if book.get_reviews %}
             {%for rev in book.get_reviews %}
              {% if rev.details%}

                 <p style="color: #000066"><b>{{rev.post_details}}</b></p>
        {% if request.user.is_authenticated and request.user.is_admin and request.user == rev.user %}
    <script>var deleteurl{{rev.pk}} = '{% url "archives:deletereview" rev.pk %}';</script>
    <p><a style="text-decoration: underline; color: #000066" onclick="removereview(deleteurl{{rev.pk}})">Remove the review </a></p>
    {% endif %}

                  <p>{{rev.details|linebreaks }}</p>
              {% endif %}

             {%endfor%}

           {% endif %}

    </div>

</div>

aaa/home/templates/home/basetemplates/homecontainer.html
{% load static %}
<div class="home-container">


      <div class="someclass">
        <div class="blue-block flex-column">
        <p class="center">  <a   href="{% url 'home:postForm'  %}" >Add POST | QUESTION</a> |  <a href="{% url 'archives:createconference' %}?createconference=True"> CONFERENCE</a> | <a href="{% url 'archives:createlecture' %}"> LECTURE</a></p>

        </div>
        {% if lectures %}
        <h2 class="tagbreak">#Lectures</h2>

        {% for post in lectures %}
        {% include "home/basetemplates/lecturebase.html" %}
        {% endfor %}
        {% endif %}


{% if questionbank or flashcards %}
{% include "home/basetemplates/qbcover.html" %}

{% endif %}

        {% if conferences or oldposts %}
        <h2 class="tagbreak">#Conferences</h2>

        {% for post in conferences %}
        {% include "home/basetemplates/conferencebase.html" %}
        {% endfor %}
        {% for post in oldposts  %}
        {% include "home/basetemplates/homepost.html" %}
        {% endfor %}

        {% endif %}



        {% if posts and request.user%}
        <h2 class="tagbreak">#Feed</h2>

        {% for post in posts %}
        {% include "home/basetemplates/homepost.html" %}
        {% endfor  %}
        {% endif  %}

      <p style="align-self: center" class="bold-red" onclick="needmore(this)">More posts</p>


<a class="more"></a>
  </div>




    </div>

aaa/home/templates/home/basetemplates/lecturebase.html
{% load static %}


<div class="home-post lecture">

  <div class="flex-column">
    <div class="flex-row" style="justify-content: space-between">
      <h2 style="color: #800000; margin-bottom: 0"> {{ post.get_lecture_range }}</h2>
      <div class="socialmediatags tags">
        <a href="https://api.whatsapp.com/send?text={{ post.get_absolute_url }}" data-action="share/whatsapp/share"><img src="{% static 'home/images/whatsapp.png' %}" height=20px, width=20px alt=""> </a>

 <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={{ post.get_absolute_url }}" ><img src="{% static 'home/images/facebook.png' %}" height=20px, width=20px alt=""></a>
 <a onclick="navigator.clipboard.writeText('{{ post.get_absolute_url }}'); alert('link: {{ post.get_absolute_url }}')"><img src="{% static 'home/images/copy.png' %}" height=20px, width=20px alt=""></a>


      </div>
    </div>


      <div class="regulartags tags">
        {% for tag in post.get_tags %}
        {% if tag.is_degree %}
        <p class="degree"><a style="margin:5px;text-decoration:none;color: white;" href="{% url 'home:speciality' tag.name %}">{{tag.name}}</a></p>
        {% else %}
        {% if tag.name == 'Conferences' %}

        <p style="text-decoration:none; font-weight: 400;margin-right: 10px;text-align: center;" ><a id = '{{tag.name}}' style="margin: 5px;text-decoration: none" href="{% url 'home:conf' %}">{{tag.name}}</a>  </p>

        {% else %}
        <p style="text-decoration:none; font-weight: 400;margin-right: 10px;text-align: center;" ><a id = '{{tag.name}}' style="margin: 5px;text-decoration: none" href="{% url 'home:speciality' tag.name %}">{{tag.name}}</a>  </p>

        {% endif %}

        {% endif %}
        {% endfor %}
      </div>


  </div>
  <p style="color: #000066"><b>{{post.posted_on}} </b></p>

  <div class="home-post-heading">
      <h3>{{post.heading | linebreaks }}</h3>

      {% if request.user.is_authenticated and request.user == post.user or request.user.is_admin%}
     <form onsubmit="deleteposte(event, {{post.pk}})" method="post" enctype="application/x-www-form-urlencoded">
     {% csrf_token %}
      <input type="submit" name = 'deletepostbtn{{post.pk}}' value="Delete Lecture" style="text-decoration: underline;color: white; background-color: #800000;" >
     </form>
     {%endif %}



  </div>

 {% if post.img %}
 <div class="home-post-img">
     <img  src="/media/{{post.img}}" width="250px" height="250px">
 </div>
 {% endif  %}

 {% if request.user.is_admin and request.user == post.user %}
 <p><a href="{% url 'archives:adddetail' post.pk %}"><img src="{% static 'home/images/details.png' %}" height="30px" width="30px" alt=""></a></p>
 {% endif %}

 {% if post.get_post_details %}
 {% for i in post.get_post_details %}
 <div class="showsubjectintro">

 <h2 style="text-decoration: underline; font-weight: 600; color: #000066;">{{i.heading}}
   {% if request.user.is_admin %}
   <a href="{% url 'archives:editdetails' i.pk post.pk%}"> <img src="{% static 'home/images/edit.png' %}" height="20px" width="20px" alt=""> </a><a style="margin-left: 10px" href="{% url 'archives:deletepostdetail' i.pk %}"><img src="{% static 'home/images/delete.png' %}" height="20px" width="20px"></a>

   {% endif %}
 </h2>

     {% if i.details %}
     <p>{{i.details|linebreaks }}</p>
     {% else %}
     {% endif %}
 </div>
 {% endfor %}
 {% endif %}



 {% if post.get_links %}
 <h3>Attached Links</h3>
 <form class="" action="{% url 'archives:sendmail' post.pk %}" method="post">
   {% csrf_token %}
   <button style="height: 50px;width: 80px;background-color: #000066;color:white;" type="submit" name="button"> Get Lecture link to your mail</button>
 </form>
 {% endif  %}

 {% if post.pdf %}
 <b>Attached Pdfs</b>
 <div class="home-post-pdf">
     <a href="/media/{{post.pdf}}"><p>{{post.pdf_name}}: /media/{{post.pdf}}</p></a>
 </div>
 {% endif  %}
 
 <div class="blue-block flex-column" onclick="showcommentsdh('comments{{ post.pk  }}')"  style="min-height: 40px">
   {% if request.user.is_authenticated and request.user.is_staff %}
   <a >{{ post.get_comments_length }}</a>
   {% elif request.user.is_authenticated and request.user.is_staff == False %}
   <a>You have visitor privileges and need to be approved by Admin to interact in the website.</a>

   {% else %}
   <a href="{% url 'accounts:login' %}">Login to see/post comments</a>
   {% endif %}

 </div>
 {% if request.user.is_staff %}
 <div id="comments{{post.pk}}" class="comments ">
   <script type="text/javascript">
     var dhcomments{{post.pk}} = document.getElementById('comments{{ post.pk }}')
     dhcomments{{post.pk}}.style.display = 'none';
   </script>
 {% if post.get_comments %}
 <div class="home-post-comments">
 {% for comment in post.get_comments %}
     <div class="home-post-comment-single">
         <div class="flex-row end-end">
           <p style="font-size: 14px;text-decoration:underline;color: #000066"><b>{{comment.user.username}} | {{comment.posted_on}}  </b>   </p>
           {% if request.user.is_staff and request.user == comment.user%}
           <p><a style="margin-right: 3px" onclick="deletecomment(event, {{comment.pk}})"><img src="{% static 'home/images/delete.png' %}" height="20px" width="20px" alt=""></a></p>
               {%endif %}
         </div>


   {% if comment.img %}

 <div  class="home-post-img">
     <img  src="/media/{{comment.img}}" width="250px" height="250px">
 </div>

 {% endif  %}



 {% if comment.text %}
 <div class="home-post-content">
     <p>{{comment.text|linebreaks }}</p>
 </div>
 {% endif  %}




 {% if comment.get_links %}
         <b>Attached links</b>
 {% for i in comment.get_links %}
 <div class="home-post-link">
     <a href="{{i.link}}"><p>{{i.link_name}}: {{i.link}}</p></a>
 </div>
 {%endfor%}
 {% endif  %}
 {% if comment.pdf %}
         <b>Attached pdfs</b>
 <div class="home-post-pdf">
     <a href="{{comment.pdf}}"><p>{{comment.pdf_name}}: {{comment.pdf}}</p></a>
 </div>
 {% endif  %}
         </div>
 {% endfor %}
 </div>
 {% endif  %}
 {% if request.user.is_staff %}
 <div class="comment-create-form">
  <form enctype="multipart/form-data" method="post" action="{% url 'home:commentform' post.pk %}">
         {% csrf_token %}
     <p><textarea required type="text" name="text" placeholder="Enter Comment.."></textarea></p>

     <button name="createcomment" type="submit" value="createcomment">Submit</button>
     </form>

     </div>
 {% endif %}

 </div>
 {% endif %}
 </div>

aaa/home/templates/home/basetemplates/qablock.html
{% load static %}
<div class="qa">
               <b style="align-self: flex-start; background-color: #000066; color: white;"> {% if request.user.is_authenticated and request.user == post.user or request.user.is_admin%}
<form onsubmit="deletequestion(event, {{post.pk}})" method="post" enctype="application/x-www-form-urlencoded">
{% csrf_token %}
<input  type="submit" name = 'deletepostbtn{{post.pk}}' value="Delete" style="text-decoration: underline; color: #000066" >
</form>
{%endif %}</b>

    <p>{{post.question|linebreaks}}</p>
    <p>{{post.answer|linebreaks}}</p>

</div>