aaa/aaa/urls.py
from django.shortcuts import redirect
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.contrib.auth import views
from django.contrib.auth import authenticate, login
def newlogin(request):
    return redirect('accounts:login')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('archives/', include('archives.urls')),
    path('stats/', include('stats.urls')),
    path('accounts/', include('accounts.urls')),
    path('mcq/', include('mcq.urls')),
    path('notifications/', include('notifications.urls')),
]
if settings.DEBUG:
    urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, {
    'document_root':settings.MEDIA_ROOT
    })
    ]

aaa/mcq/urls.py
from django.urls import path
from . import views
app_name = 'mcq'

urlpatterns = [

path('', views.McqView.as_view(), name = 'qa'),
path('<str:pk>', views.McqView.as_view(), name='subjectquestions'),
path('refreshquestions', views.refresh_questions_view, name='refreshq'),
path('createquestions/<str:type>', views.CreateQuestion.as_view(), name='createq'),
path('getnewquestions/<str:index>', views.GetQuestions.as_view(), name='getq'),
path('deletequestions/<int:pk>', views.delete_question_view, name = 'deleteq'),
path('question/<int:qpk>', views.QuestionDetail.as_view(), name = 'qdetail'),
]

aaa/home/models.py
from django.db import models
from urllib.parse import urlparse, parse_qs
import datetime, pytz, humanize
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys,os
from django.utils import timezone
from accounts.models import User
from django.conf import settings
# Create your models here.
print(os.getcwd())


class ImageAdd(models.Model):
    user = models.ForeignKey(User, on_delete= models.SET_NULL, null = True, blank = True )
    name = models.CharField(max_length=20, blank=True, null=True)
    img = models.ImageField(blank=True, null = True, upload_to = 'contentfeedImages/%Y/%m/$D/')

    def compressImage(self, image):
        im = Image.open(image)
        output = BytesIO()
        if im.mode != 'RGB':
            im = im.convert('RGB')
        im = im.resize((900, 600))
        im.save(output, format='JPEG', quality=60)
        output.seek(0)
        newimage = InMemoryUploadedFile(output, 'ImageField', '%s.jpg' % image.name.split('.')[0], 'image/jpeg',
                                        sys.getsizeof(output), None)
        return newimage

    def save(self, *args, **kwargs):
        if self.img:
            self.img = self.compressImage(self.img)
        super(ImageAdd, self).save(*args, **kwargs)

class PostLink(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    link= models.URLField(blank=True, null=True, max_length=400)
    link_name = models.CharField(blank=True, null=True, max_length=50)
    def __str__(self):
        return self.link_name

class Tag(models.Model):
    name = models.CharField(max_length=40, blank=True, null=True)
    is_speciality=models.BooleanField(default=False)
    is_degree = models.BooleanField(default=False)
    details=models.ManyToManyField('accounts.ProfileDetail', blank=True)

    @property
    def get_questions(self):
        try:
            return self.questionbank_set.all()
        except:
            return False
    @property
    def get_details(self):
        d = list(self.details.all().order_by('pk'))
        if len(d) >= 1:
            return d
        else:
            return False
    def __str__(self):
        try:
            if self.name:
                return self.name
            else:
                return str(self.pk)
        except:
            return 'some problem in tag object'

    def get_books(self):
        if self.is_degree:
            a = self.book_set.all()
            if a:
                return list(a)
            else:
                return False
        else:
            return False

class Comment(models.Model):
    date = models.DateTimeField(default=timezone.make_aware(datetime.datetime.now(), timezone.get_default_timezone()))
    user = models.ForeignKey(User, on_delete= models.SET_NULL, null = True, blank = True )
    text = models.TextField(max_length=500, blank=True, null=True)
    img = models.ImageField(blank=True, null = True, upload_to = 'commentimages/%Y/%m/$D/')
    link = models.ManyToManyField(PostLink, blank=True, null=True)
    pdf = models.FileField(blank=True, null=True, upload_to='commentsPosts/pdf/%Y/%m/$D/')
    pdf_name = models.CharField(blank=True, null=True, max_length=50)
    def __str__(self):
        try:
            if self.text:
                return self.text
            else:
                return 'no text added'
        except:
            return 'some problem in comment object'

    def compressImage(self, image):
        im = Image.open(image)
        output = BytesIO()
        if im.mode != 'RGB':
            im = im.convert('RGB')
        im = im.resize((900, 600))
        im.save(output, format='JPEG', quality=60)
        output.seek(0)
        newimage = InMemoryUploadedFile(output, 'ImageField', '%s.jpg' % image.name.split('.')[0], 'image/jpeg',
                                        sys.getsizeof(output), None)
        return newimage

    def save(self, *args, **kwargs):
        if self.img:
            self.img = self.compressImage(self.img)
        super(Comment, self).save(*args, **kwargs)

    def get_images(self):
        a = self.img.all()
        if len(a) < 2:
            return list(a)
        else:
            return a

    def get_links(self):
        a = self.link.all()
        if len(a) < 2:
            return list(a)
        else:
            return a
    def get_user(self):
        if self.user is None:
            return 'Anonymous'
        if self.user.is_admin:
            return 'Admin'
        elif self.user.is_staff:
            return self.user.username
        else:
            return 'Anonymous'

    def posted_on(self):
        try:
            #x = '{0}  |  {1} '.format(self.user.username, self.date.strftime('%d %b %Y %I %M %p'))
            x = '{0}  |  {1} '.format(self.get_user(), self.date.strftime('%d %b %Y %I %M %p'))

            return x
        except:
            return 'Group Admin'


class Post(models.Model):
    date = models.DateTimeField(auto_now_add=True,auto_now=False, null=True)
    user = models.ForeignKey(User, on_delete= models.SET_NULL, null = True, blank = True )
    heading = models.CharField(max_length=1000, null=False, blank=False)
    img = models.ImageField(blank=True, null=True, upload_to='Postimages/%Y/%m/$D/')
    link = models.ManyToManyField(PostLink, blank=True, null=True)
    pdf = models.FileField(blank=True, null=True, upload_to='homePosts/pdf/%Y/%m/$D/')
    pdf_name = models.CharField(blank=True, null=True, max_length=50)
    content=models.CharField(max_length=1000,blank=True, null=True)
    comments = models.ManyToManyField(Comment, blank=True, null=True)
    tag = models.ManyToManyField(Tag)
    lecture = models.BooleanField(default=False, null = True, blank = True)
    conference = models.BooleanField(default=False, null = True, blank = True)
    def __str__(self):
        try:
            if self.heading:
                return self.heading
            elif self.user:
                return self.user.username
            elif self.date:
                return self.posted_on
            else:
                return 'no heading'
        except:
            return 'some problem in post object'
    def get_text(self):
        text = []
        text.append('Checkout post: {0}'.format(self.get_absolute_url()))
        text.append(self.heading)
        if self.content:
            text.append(self.content)

        if self.link.all():
            for i in self.link.all():
                text.append(i.link)

        return '\n\n'.join(text)
    def get_absolute_url(self):
        if settings.DEBUG:
            return 'http://127.0.0.1:8000/posts/{}'.format(self.pk)
        else:
            return 'https://allaboutanaesthesia.co/posts/{}'.format(self.pk)

    def compressImage(self, image):
        im = Image.open(image)
        output = BytesIO()
        if im.mode != 'RGB':
            im = im.convert('RGB')
        im = im.resize((900, 600))
        im.save(output, format='JPEG', quality=60)
        output.seek(0)
        newimage = InMemoryUploadedFile(output, 'ImageField', '%s.jpg' % image.name.split('.')[0], 'image/jpeg',
                                        sys.getsizeof(output), None)
        return newimage

    def save(self, *args, **kwargs):
        if self.img:
            self.img = self.compressImage(self.img)
        super(Post, self).save(*args, **kwargs)
    def get_comments(self):
        a = self.comments.all()
        if len(a) < 2:
            return list(a)
        else:
            return a
    @property
    def get_comments_length(self):
        x = list(self.comments.all())
        if x:
            return '{0} comments present, click to view.'.format(len(x))
        else:
            return 'No comments added, click to add comments'
    def get_tags(self):
        a = self.tag.all()
        if len(a) < 2:
            return list(a)
        else:
            return a



    def get_links(self):
        a = self.link.all()
        if len(a) < 2:
            return list(a)
        else:
            return a
    def get_user(self):
        if self.user is None:
            return 'Anonymous'
        if self.user.is_admin:
            return 'Admin'
        elif self.user.is_staff:
            return self.user.username
        else:
            return 'Anonymous'

    @property
    def posted_on(self):
        timezone = pytz.timezone('Asia/Kolkata')
        today = datetime.datetime.now(timezone)
        difference = today - pytz.utc.localize(self.date)
        difference = humanize.naturaldelta(difference)
        try:
            #x = '{0}  |  {1} '.format(self.user.username, self.date.strftime('%d %b %Y %I %M %p'))
            x = '{0}  |  {1} ago'.format(self.user.username, difference)

            return x
        except:
            return 'Group Admin'

aaa/mcq/models.py
from django.db import models
from accounts.models import User
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys
from django.conf import settings
# from home.models import Tag
# Create your models here.

class QTag(models.Model):
    name = models.CharField(max_length=20, blank=False)
    subject = models.BooleanField(default=False)
    degree = models.BooleanField(default=False)
    def __str__(self):
        try:
            return self.name
        except:
            return 'some problem in tag object'
    @property
    def get_questions(self):
        try:
            return self.questionbank_set.all()
        except:
            return False

    @property
    def is_degree(self):
        if self.degree:
            return True
        else:
            return False

    @property
    def is_subject(self):
        if self.subject:
            return True
        else:
            return False


class QuestionBank(models.Model):
    tag = models.ManyToManyField('home.Tag', null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    links = models.ManyToManyField('home.PostLink', blank=True)
    date = models.DateField(auto_now_add=True)
    question = models.CharField(max_length=1000000, blank=True, null=True)
    answer = models.CharField(max_length=1000000, blank=True, null=True)
    mcq = models.BooleanField(default=False)
    flashcard = models.BooleanField(default=False)
    qa = models.BooleanField(default=False)

    def __str__(self):
        try:
            return self.question
        except:
            return str(self.pk)
    def get_absolute_url(self):
        if settings.DEBUG:
            return 'http://127.0.0.1:8000/mcq/question/{}'.format(self.pk)
        else:
            return 'https://allaboutanaesthesia.co/mcq/question/{}'.format(self.pk)
    @property
    def get_subjects(self):
        try:
            return list(self.tag.filter(is_speciality=True))
        except:
            return 'some problem in saving tag'
    @property
    def get_tags(self):
        try:
            return self.tag.all()
        except:
            return 'some problem in saving tag'
    @property
    def is_mcq(self):
        if self.mcq:
            return True
        else:
            return False

    @property
    def is_qa(self):
        if self.qa:
            return True
        else:
            return False

    @property
    def is_flashcard(self):
        if self.flashcard:
            return True
        else:
            return False

    @property
    def get_question_image(self):
        try:
            x = self.qimage_set.get(qimage = True)
            return x.image.url
        except:
            return False

    @property
    def get_answer_image(self):
        try:
            x = self.qimage_set.get(aimage=True)
            return x.image.url
        except:
            return False


    @property
    def get_links(self):
        try:
            x= self.links.all()
            return list(x)
        except:
            return False

class Qimage(models.Model):
    qinstance = models.ForeignKey(QuestionBank, on_delete=models.SET_NULL, null =True, blank=True)
    image = models.ImageField(upload_to='Questionbank/', blank=True, null=True)
    aimage = models.BooleanField(default=False)
    qimage = models.BooleanField(default=False)

    def compressImage(self, image):
        im = Image.open(image)
        output = BytesIO()
        if im.mode != 'RGB':
            im = im.convert('RGB')
        im = im.resize((900, 600))
        im.save(output, format='JPEG', quality=60)
        output.seek(0)
        newimage = InMemoryUploadedFile(output, 'ImageField', '%s.jpg' % image.name.split('.')[0], 'image/jpeg',
                                        sys.getsizeof(output), None)
        return newimage

    def save(self, *args, **kwargs):
        if self.image:
            self.image = self.compressImage(self.image)
        super(Qimage, self).save(*args, **kwargs)

aaa/mcq/templates/mcq/basepage.html
{% extends 'home/base.html' %}
{% load static %}

{% block main %}


{% if general %}

<style>
.arch-box{
    width: 250px;
    height: 250px;
}
@media screen and (max-width: 800px) {
    .arch-box{
      width: 100%;
      margin: 0;
      margin-top: 50px;
    }
    .arch-main{
      width: 100%;
    }
    .arch-row{
      width: 100%;
    }
}
</style>
<div class="arch-main">
<h1 style="align-self: center">Question Bank</h1>
    <div class="arch-row">
        {% for tag in tag_speciality %}
     <div class="arch-box">
         <h2><a href="{% url 'mcq:subjectquestions' tag.pk %}">{{tag.name}}</a> </h2>
     </div>
        {% endfor %}
    </div>
</div>



{% else %}
<style>
    .mcqcover{
        display: flex;
        flex-flow: column;
        justify-content: space-between;
        font-family: 'Source Serif Pro', serif;
        font-size: 15px;
        line-height: 25px;
    }
    .questionbankheading{
        display: flex;
        flex-flow: column wrap;
        align-items: center;
        color: #FFFFE0;
        font-weight: 100;
        background-color: #800000;
        margin-bottom: 25px;
    }
    .questionbankheading a{
        color: #FFFFE0;
    }
    .mcqcover a{
        text-decoration: underline;
        font-weight: 500;
    }
    .mcqbox{
        display: flex;
        flex-flow: column wrap;
        justify-content: center;
        align-items: center;
    }
    .mcqblock{
        display: none;
        flex-flow: column wrap;
        border-bottom: 5px outset blue;
        border-right: 5px outset blue;
        border-top: 1px groove gray;
        justify-content: space-between;
        margin: 50px 0 50px 0;
        min-height: 350px;
        width: 600px;
    }
    .mcqblock p {
        margin: 5px;
    }
    .flashcardbox{
        display: flex;
        flex-flow: column wrap;
        justify-content: center;
        align-items: center;
    }

    .flashcardblock{
        display: none;
        min-height: 350px;
        width: 600px;
        margin: 50px 0 50px 0;
        background-color: #FFDAB9;
        flex-flow: column wrap;
        justify-content: center;
        align-items: center;



    }
    .flashcards {
        background-color: white;
        display: flex;
        flex-flow: column wrap;
        width: 92%;
        align-items: center;
        min-height: 280px;
        border:10px solid  #FFDAB9 ;
        justify-content: center;

    }
    .qabox{
        display: flex;
        flex-flow: column wrap;
        justify-content: flex-start;
        align-items: flex-start;
        height: auto;
    }
    .qa{
        font-family: 'Source Serif Pro', serif;
        font-size: 15px;
        text-space: 5px;
        line-height: 25px;
    }

     @media screen and (max-width: 800px) {
         .mcqblock{
            width: 100%;
             margin: 0;
             margin-bottom: 20px;
        }
        .flashcardblock{
            width:100%;
             margin: 0;
            margin-bottom: 20px;
        }
        .qa{
            width: 100%;
             margin: 0;
        }
        .flashcardanswer {
          margin:0;
        }
     }
</style>
<div class="mcqcover">
    
    <div class="questionbankheading">
         <h1 >{{tag.name}}</h1>
    <h2 >Question bank </h2>
    <b  > Add  <a href="{% url 'mcq:createq' 'mcq'  %}">Mcq</a> | <a href="{% url 'mcq:createq'  'flashcard' %}">Flashcards</a> | <a href="{% url 'mcq:createq' 'qa'  %}">Case</a> </b>

    </div>

    <div  class="mcqbox">
        <h3 style="align-self: flex-start; ">MCQ based Questions</h3>
        <b style="align-self: flex-start" >Add <a href="{% url 'mcq:createq' 'mcq'  %}">Mcq</a></b>
        {% for post in questionbank %}
        {% if post.is_mcq %}
        {% include "home/basetemplates/mcqblock.html" %}
        {% endif %}
        {% endfor %}





    </div>
    <div class="flashcardbox">
        <h3 style="align-self: flex-start">Flash Cards</h3>
        <b style="align-self: flex-start">Add  <a href="{% url 'mcq:createq'  'flashcard' %}">Flashcards</a></b>
            {% for post in flashcards %}
        {% if post.is_flashcard %}
        {% include "home/basetemplates/flashcardblock.html" %}
        {% endif %}
        {% endfor %}
        </div>
    <div class="qabox">
        <h3>Case Based Questions</h3>
        <p  >Add <a href="{% url 'mcq:createq' 'qa'  %}">Case</a> </p>

        {% for post in cases %}
        {% if post.is_qa %}
        {% include "home/basetemplates/qablock.html" %}
        {% endif %}
        {% endfor %}
    </div>
    <div class="testing">

    </div>

</div>
<script>
var mcqbox = document.getElementsByClassName('mcqbox')[0];
var flashcardbox = document.getElementsByClassName('flashcardbox')[0];
var mcqblock = document.getElementsByClassName('mcqblock');
var flashcardblock= document.getElementsByClassName('flashcardblock');
var testing = document.getElementsByClassName('testing')[0];
var startx;
var starty;
var endx;
var endy;

var xdist;
var ydist;
var starttime;
var endtime;
var elapsedtime;






function deletequestion(e,pk) {
    e.preventDefault();
    var message = confirm('Are you sure you want to delete the post');
    if (message==true){
        var dhttp = new XMLHttpRequest();
        dhttp.onreadystatechange = function() {
        if (this.readyState == 4 ) {

         var x = JSON.parse(this.responseText);
         console.log(x.success) ;
         window.location.href = x.success;

        }
                                                };
        console.log("");

        dhttp.open('POST', '/mcq/deletequestions' + '/' + pk );
        dhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        dhttp.send("csrfmiddlewaretoken=" +document.getElementsByName('csrfmiddlewaretoken')[0].value +  "&deletepostbtn=Deletepost");

        console.log(true);
    }
    else{
        console.log(false);
    }
}
function revealmcq( element) {
element.style.display = 'block';
}
function showflashcard(x,q, a) {
    q.style.display = 'none';
    a.style.display='block';
    x.style.display = 'none';

}

function needmore(x,type, classname) {

    newhttp = new XMLHttpRequest();

    newhttp.onreadystatechange = function() {
  if (this.readyState == 4 && this.status == 200) {
      console.log('text recieved');
      jsontext = JSON.parse(this.responseText);
      console.log(jsontext.length);
      console.log(mcqblock.length);
      var box = document.getElementsByClassName(x[0].parentNode.className);
      console.log(box);
      for (var i=0; i<jsontext.length; i++) {
          console.log(jsontext[i]);
          var mcq = document.createElement('div');

          mcq.innerHTML = jsontext[i];
          mcq.classList.add(classname);

          box[0].append(mcq);
      }
      console.log(x.length);



  }
};
    newhttp.open('GET', "/mcq/getnewquestions" + "/"+x.length +'?type=' + type + '&tag=' +'{{tag.pk}}');
    newhttp.send();
    }

   mcqbox.addEventListener('touchstart', function (e) {
       console.log(e);
       var touchobj = e.changedTouches[0];
       startx = touchobj.pageX;
       starty = touchobj.pageY;
       starttime = new Date().getTime();
       testing.innerHTML = x +" , " + y;


   }, false);

   mcqbox.addEventListener('touchend', function (e) {
       console.log(e);
       var touchobj = e.changedTouches[0];
       endx = touchobj.pageX;
       endy = touchobj.pageY;

       endtime = new Date().getTime();
       elapsedtime = (endtime - starttime)/1000;
       xdist = endx-startx;
       ydist = endy-starty;
       if (elapsedtime <= 2) {
           if (Math.abs(xdist) >= 30 && Math.abs(ydist) <=100 ){
              if (xdist > 0){
                  for (var i = 0; i <mcqblock.length; i++) {
                      if (window.getComputedStyle(mcqblock[i]).display == 'flex'){

                          if (i-1 >= 0) {
                              mcqblock[i-1].style.display = 'flex';
                              mcqblock[i].style.display = 'none';
                              break;
                          } else {
                              console.log('NOOOoooooo');
                              testing.innerHTML = xdist +" , " + ydist + " , " + " swipe towards right" + "Reached END" ;
                          }

                      }
                  }


              } else {
                  for (var i = 0; i <mcqblock.length; i++) {
                      if (window.getComputedStyle(mcqblock[i]).display == 'flex'){

                          if (i < mcqblock.length-1) {
                              mcqblock[i+1].style.display = 'flex';
                              mcqblock[i].style.display = 'none';
                              break;
                          } else {
                              needmore(document.getElementsByClassName('mcqblock'), 'mcq', 'mcqblock');
                              testing.innerHTML = xdist +" , " + ydist + " , " + " swipe towards left" + "Reached END" ;

                          }

                      }
                  }
              }

           }
       }



   }, false);



   flashcardbox.addEventListener('touchstart', function (e) {
       console.log(e);
       var touchobj = e.changedTouches[0];
       startx = touchobj.pageX;
       starty = touchobj.pageY;
       starttime = new Date().getTime();
       testing.innerHTML = x +" , " + y;


   }, false);


 flashcardbox.addEventListener('touchend', function (e) {
       console.log(e);
       var touchobj = e.changedTouches[0];
       endx = touchobj.pageX;
       endy = touchobj.pageY;

       endtime = new Date().getTime();
       elapsedtime = (endtime - starttime)/1000;
       xdist = endx-startx;
       ydist = endy-starty;
       if (elapsedtime <= 2) {
           if (Math.abs(xdist) >= 30 && Math.abs(ydist) <=100 ){
              if (xdist > 0){
                  for (var i = 0; i <flashcardblock.length; i++) {
                      if (window.getComputedStyle(flashcardblock[i]).display == 'flex'){

                          if (i-1 >= 0) {
                              flashcardblock[i-1].style.display = 'flex';
                              flashcardblock[i].style.display = 'none';
                              break;
                          } else {
                              console.log('NOOOoooooo');
                              testing.innerHTML = xdist +" , " + ydist + " , " + " swipe towards right" + "Reached END" ;
                          }

                      }
                  }


              } else {
                  for (var i = 0; i <flashcardblock.length; i++) {
                      if (window.getComputedStyle(flashcardblock[i]).display == 'flex'){

                          if (i < flashcardblock.length-1) {
                              flashcardblock[i+1].style.display = 'flex';
                              flashcardblock[i].style.display = 'none';
                              break;
                          } else {
                              needmore(document.getElementsByClassName('flashcardblock'), 'flashcard', 'flashcardblock');
                              testing.innerHTML = xdist +" , " + ydist + " , " + " swipe towards left" + "Reached END" ;

                          }

                      }
                  }
              }

           }
       }



   }, false);

    function nextquestion(block, type, classname) {
        console.log(block);
        for (var i = 0; i <block.length; i++) {
                      if (window.getComputedStyle(block[i]).display == 'flex'){

                          if (i < block.length-1) {
                              block[i+1].style.display = 'flex';
                              block[i].style.display = 'none';
                              break;
                          } else {
                              needmore(block, type, classname);
                              testing.innerHTML = xdist +" , " + ydist + " , " + " swipe towards left" + "Reached END" ;}}}
    }
    function previousquestion(block) {
        console.log(block);
        for (var i = 0; i <block.length; i++) {
                      if (window.getComputedStyle(block[i]).display == 'flex'){

                          if (i-1 >= 0) {
                              block[i-1].style.display = 'flex';
                              block[i].style.display = 'none';
                              break;
                          } else {
                              console.log('NOOOoooooo');
                              testing.innerHTML = xdist +" , " + ydist + " , " + " swipe towards right" + "Reached END" ;}}}
    }


</script>
{% endif %}
{% endblock %}

aaa/mcq/templates/mcq/qbankform.html
{% extends 'home/base.html' %}
{% load static %}

{% block main %}

<style>
    .tagrow{
        flex-grow: 1;
        align-items: flex-start;
        height: 200px;
    }
    #id_heading{
        border: none;
    }

    .errorlist li {
        font-size: 20px; color: red; font-weight: 700;
    }
    @media screen and (max-width: 800px) {
        .tagrow{
            height: auto;
        }

    }
</style>


<div class="fullcover">
    <div class="postform">

        <form style="display: flex;flex-flow: column wrap" method="post" enctype="multipart/form-data">
            {% if form.errors %}

            <p >{{form.errors}}</p>

            {% endif %}
    {% csrf_token %}

            {% if tags %}
            <p><b>Kindly select a tag:</b></p>
            <div class="tagform" style="display: flex; flex-flow: row wrap">


           <div class="tagrow" style="display: flex; flex-flow: column wrap">
               {% for tag in tags %}

               {% if tag.is_speciality %}
                <p><label for="id_tag_1"><input type="checkbox" name="tag" value="{{tag.pk}}" placeholder="Tags" id="id_tag_{{tag.pk}}">
 {{tag.name}}</label></p>
               {% endif %}
            {% endfor %}
           </div>


            </div>
     {% endif %}

{% if type == 'mcq' %}
            <style>
                 #id_answer{
        font-family: 'Overlock', cursive;
    border-radius: 4px;
    width: 95% ;
    height:auto;
    font-size: 20px;
    border: none;
    }
                #id_heading {
                    min-height: 400px ;
                }
            </style>
                <textarea type="text" name = 'question' maxlength="100000" placeholder="Enter Mcq question along with options " required id="id_heading" ></textarea>

     <p>Add Image for Question (optional):  <input type="file" name=" qimage" ></p>
            <textarea  type="text" name = 'answer' maxlength="100000" placeholder="Type correct answer for above mcq" required id="id_answer" ></textarea>
     <p>Add Image for Answer (optional):  <input type="file" name=" aimage" ></p>
{% endif %}

{% if type == 'flashcard' %}
            <style>
                 #id_answer{
        font-family: 'Overlock', cursive;
    border-radius: 4px;
    width: 95% ;
    min-height:300px;
    font-size: 20px;
    border: none;
    }
                #id_heading {
                    min-height: 100px ;
                }
            </style>
                <textarea type="text" name = 'question' maxlength="200" placeholder="Enter Question for flashcard " required id="id_heading" ></textarea>

     <p>Add Image for Flashcard Question (optional):  <input type="file" name=" qimage" ></p>
            <textarea  type="text" name = 'answer' maxlength="5000" placeholder="Type Answer for Flashcard" required id="id_answer" ></textarea>
     <p>Add Image for Flashcard Answer (optional):  <input type="file" name=" aimage" ></p>
{% endif %}

{% if type == 'qa' %}
            <style>
                 #id_answer{
        font-family: 'Overlock', cursive;
    border-radius: 4px;
    width: 95% ;
    min-height:500px;
    font-size: 20px;
    border: none;
    }
                #id_heading {
                    min-height: 600px ;
                }
            </style>
                <textarea type="text" name = 'question' maxlength="100000" placeholder="Enter Case Along with Questions  " required id="id_heading" ></textarea>

     <p>Add Image for Case (optional):  <input type="file" name=" qimage" ></p>
            <textarea  type="text" name = 'answer' maxlength="150000" placeholder="Enter Case discussions along with answers" required id="id_answer" ></textarea>
     <p>Add Image for Case Explanation (optional):  <input type="file" name=" aimage" ></p>
{% endif %}
    <p>Add Links (optional)</p>
              <div id="addlinkform{{post.pk}}">
                 <p><input type="text"  placeholder="Add link name.." maxlength="20" name="link_name" value="">: <input type="url" placeholder="Add link url.." value="" maxlength="200"  name="link"></p>
             </div>
             <p style="text-decoration: underline;color: #000066;"><a onclick="addnewforms('addlinkform')"> Add more links</a></p>

    <button style="align-self: center" name="qbank" value="qbank" type="submit">Submit</button>

</form>

    </div>
</div>
{% endblock %}

aaa/mcq/templates/mcq/question.html
{% extends "home/base.html" %}
{% load static %}
{% block main %}

{% endblock %}