aaa/aaa/urls.py
from django.shortcuts import redirect
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.contrib.auth import views
from django.contrib.auth import authenticate, login
def newlogin(request):
    return redirect('accounts:login')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('archives/', include('archives.urls')),
    path('stats/', include('stats.urls')),
    path('accounts/', include('accounts.urls')),
    path('mcq/', include('mcq.urls')),
    path('notifications/', include('notifications.urls')),
]
if settings.DEBUG:
    urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, {
    'document_root':settings.MEDIA_ROOT
    })
    ]

aaa/archives/urls.py
from django.urls import path
from . import views

app_name = 'archives'


urlpatterns = [
    path('', views.ArchivePage.as_view(), name = 'home_archives'),
    path('lecturepost/<int:pk>', views.LecturePostDetailView.as_view(), name = 'lecture_detail'),
    path('conferencepost/<int:pk>', views.ConferencePostDetailView.as_view(), name = 'conference_detail'),
    path('exfactor', views.LecturePage.as_view(), name = 'lectures'),
    path('lectures', views.LecturePage.as_view(), name = 'lectures'),
    path('send-mail/<int:pk>', views.send_mail_view, name = 'sendmail'),
    path('deletepost-detail/<int:pk>', views.delete_post_detail, name = 'deletepostdetail'),
    path('edit-lecture-detail/<int:pk>/<int:opk>', views.ProfileDetailUpdateView.as_view(), name = 'editdetails'),
    path('edit-lecture-detail/<int:opk>', views.ProfileDetailCreateView.as_view(), name = 'adddetail'),
    path('edit-lecture/<int:pk>', views.LecturePostUpdateView.as_view(), name = 'updatelecture'),
    path('delete-link/<int:pk>', views.PostLinkDeleteView.as_view(), name = 'deletelink'),
    path('edit-links/<int:pk>/<int:opk>', views.PostLinkUpdateView.as_view(), name = 'editlinks'),
    path('create-lecture', views.LecturePostCreateView.as_view(), name = 'createlecture'),
    path('create-conference', views.LecturePostCreateView.as_view(),kwargs={'conference':True}, name = 'createconference'),
    path('details', views.ArchDetail.as_view(), name = 'archdetail'),
    path('testing', views.Test.as_view(), name='test'),
    path('del/<int:pk>', views.delete_book_view, name='deletebook'),
    path('delreview/<int:pk>', views.delete_review_view, name='deletereview')
]

aaa/home/urls.py
from django.urls import path
from . import views
from archives import views as archviews
from .models import Tag


app_name = 'home'

urlpatterns = [
path('posts/<int:pk>', views.PostDetail.as_view(), name = 'postdetail'),
path('users/<str:username>', views.YourPost.as_view(), name = 'yourposts'),
path('getnewposts/<int:pk>', views.GetPosts.as_view(), name = 'getposts'),
path('', views.HomeView.as_view(), name = 'home'),
path('refreshhome', views.refresh_home_page, name = 'refresh'),
path('managewebsite', views.Manage.as_view(), name='manage'),
path('errors', views.StaffError.as_view(), name = 'stafferror'),
path('conferences', archviews.ConferencePage.as_view(), name = 'conf'),
path('searchPage', views.SearchView.as_view(), name = 'search'),
path('editdetails/<int:pk>/<int:detail_pk>', views.PostView.as_view(), name='edittagdetail'),
path('adddetails/<int:pk>', views.PostView.as_view(), name='addtagdetail'),
path('deletetag/<int:pk>/<int:detail_pk>', views.delete_tagdetail_view, name = 'deletetagdetail'),
path('delete_post/<int:pk>', views.delete_post_view, name = 'deletepost'),
path('delete_comment/<int:pk>', views.delete_comment_view, name = 'deletecomment'),
path('commentForm/<int:pk>', views.PostView.as_view(), name = 'commentform'),
path('postform', views.PostView.as_view(), name = 'postview'),
path('create_post', views.create_post_view, name='postForm'),
path('home/<str:speciality_type>', views.speciality_view, name = 'speciality')
]

aaa/mcq/urls.py
from django.urls import path
from . import views
app_name = 'mcq'

urlpatterns = [

path('', views.McqView.as_view(), name = 'qa'),
path('<str:pk>', views.McqView.as_view(), name='subjectquestions'),
path('refreshquestions', views.refresh_questions_view, name='refreshq'),
path('createquestions/<str:type>', views.CreateQuestion.as_view(), name='createq'),
path('getnewquestions/<str:index>', views.GetQuestions.as_view(), name='getq'),
path('deletequestions/<int:pk>', views.delete_question_view, name = 'deleteq'),
path('question/<int:qpk>', views.QuestionDetail.as_view(), name = 'qdetail'),
]

aaa/notifications/urls.py
from django.urls import path
from . import views

app_name = 'notifications'

urlpatterns = [
path('', views.ShowNotification.as_view(), name = 'base'),

]

aaa/home/models.py
from django.db import models
from urllib.parse import urlparse, parse_qs
import datetime, pytz, humanize
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys,os
from django.utils import timezone
from accounts.models import User
from django.conf import settings
# Create your models here.
print(os.getcwd())


class ImageAdd(models.Model):
    user = models.ForeignKey(User, on_delete= models.SET_NULL, null = True, blank = True )
    name = models.CharField(max_length=20, blank=True, null=True)
    img = models.ImageField(blank=True, null = True, upload_to = 'contentfeedImages/%Y/%m/$D/')

    def compressImage(self, image):
        im = Image.open(image)
        output = BytesIO()
        if im.mode != 'RGB':
            im = im.convert('RGB')
        im = im.resize((900, 600))
        im.save(output, format='JPEG', quality=60)
        output.seek(0)
        newimage = InMemoryUploadedFile(output, 'ImageField', '%s.jpg' % image.name.split('.')[0], 'image/jpeg',
                                        sys.getsizeof(output), None)
        return newimage

    def save(self, *args, **kwargs):
        if self.img:
            self.img = self.compressImage(self.img)
        super(ImageAdd, self).save(*args, **kwargs)

class PostLink(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    link= models.URLField(blank=True, null=True, max_length=400)
    link_name = models.CharField(blank=True, null=True, max_length=50)
    def __str__(self):
        return self.link_name

class Tag(models.Model):
    name = models.CharField(max_length=40, blank=True, null=True)
    is_speciality=models.BooleanField(default=False)
    is_degree = models.BooleanField(default=False)
    details=models.ManyToManyField('accounts.ProfileDetail', blank=True)

    @property
    def get_questions(self):
        try:
            return self.questionbank_set.all()
        except:
            return False
    @property
    def get_details(self):
        d = list(self.details.all().order_by('pk'))
        if len(d) >= 1:
            return d
        else:
            return False
    def __str__(self):
        try:
            if self.name:
                return self.name
            else:
                return str(self.pk)
        except:
            return 'some problem in tag object'

    def get_books(self):
        if self.is_degree:
            a = self.book_set.all()
            if a:
                return list(a)
            else:
                return False
        else:
            return False

class Comment(models.Model):
    date = models.DateTimeField(default=timezone.make_aware(datetime.datetime.now(), timezone.get_default_timezone()))
    user = models.ForeignKey(User, on_delete= models.SET_NULL, null = True, blank = True )
    text = models.TextField(max_length=500, blank=True, null=True)
    img = models.ImageField(blank=True, null = True, upload_to = 'commentimages/%Y/%m/$D/')
    link = models.ManyToManyField(PostLink, blank=True, null=True)
    pdf = models.FileField(blank=True, null=True, upload_to='commentsPosts/pdf/%Y/%m/$D/')
    pdf_name = models.CharField(blank=True, null=True, max_length=50)
    def __str__(self):
        try:
            if self.text:
                return self.text
            else:
                return 'no text added'
        except:
            return 'some problem in comment object'

    def compressImage(self, image):
        im = Image.open(image)
        output = BytesIO()
        if im.mode != 'RGB':
            im = im.convert('RGB')
        im = im.resize((900, 600))
        im.save(output, format='JPEG', quality=60)
        output.seek(0)
        newimage = InMemoryUploadedFile(output, 'ImageField', '%s.jpg' % image.name.split('.')[0], 'image/jpeg',
                                        sys.getsizeof(output), None)
        return newimage

    def save(self, *args, **kwargs):
        if self.img:
            self.img = self.compressImage(self.img)
        super(Comment, self).save(*args, **kwargs)

    def get_images(self):
        a = self.img.all()
        if len(a) < 2:
            return list(a)
        else:
            return a

    def get_links(self):
        a = self.link.all()
        if len(a) < 2:
            return list(a)
        else:
            return a
    def get_user(self):
        if self.user is None:
            return 'Anonymous'
        if self.user.is_admin:
            return 'Admin'
        elif self.user.is_staff:
            return self.user.username
        else:
            return 'Anonymous'

    def posted_on(self):
        try:
            #x = '{0}  |  {1} '.format(self.user.username, self.date.strftime('%d %b %Y %I %M %p'))
            x = '{0}  |  {1} '.format(self.get_user(), self.date.strftime('%d %b %Y %I %M %p'))

            return x
        except:
            return 'Group Admin'


class Post(models.Model):
    date = models.DateTimeField(auto_now_add=True,auto_now=False, null=True)
    user = models.ForeignKey(User, on_delete= models.SET_NULL, null = True, blank = True )
    heading = models.CharField(max_length=1000, null=False, blank=False)
    img = models.ImageField(blank=True, null=True, upload_to='Postimages/%Y/%m/$D/')
    link = models.ManyToManyField(PostLink, blank=True, null=True)
    pdf = models.FileField(blank=True, null=True, upload_to='homePosts/pdf/%Y/%m/$D/')
    pdf_name = models.CharField(blank=True, null=True, max_length=50)
    content=models.CharField(max_length=1000,blank=True, null=True)
    comments = models.ManyToManyField(Comment, blank=True, null=True)
    tag = models.ManyToManyField(Tag)
    lecture = models.BooleanField(default=False, null = True, blank = True)
    conference = models.BooleanField(default=False, null = True, blank = True)
    def __str__(self):
        try:
            if self.heading:
                return self.heading
            elif self.user:
                return self.user.username
            elif self.date:
                return self.posted_on
            else:
                return 'no heading'
        except:
            return 'some problem in post object'
    def get_text(self):
        text = []
        text.append('Checkout post: {0}'.format(self.get_absolute_url()))
        text.append(self.heading)
        if self.content:
            text.append(self.content)

        if self.link.all():
            for i in self.link.all():
                text.append(i.link)

        return '\n\n'.join(text)
    def get_absolute_url(self):
        if settings.DEBUG:
            return 'http://127.0.0.1:8000/posts/{}'.format(self.pk)
        else:
            return 'https://allaboutanaesthesia.co/posts/{}'.format(self.pk)

    def compressImage(self, image):
        im = Image.open(image)
        output = BytesIO()
        if im.mode != 'RGB':
            im = im.convert('RGB')
        im = im.resize((900, 600))
        im.save(output, format='JPEG', quality=60)
        output.seek(0)
        newimage = InMemoryUploadedFile(output, 'ImageField', '%s.jpg' % image.name.split('.')[0], 'image/jpeg',
                                        sys.getsizeof(output), None)
        return newimage

    def save(self, *args, **kwargs):
        if self.img:
            self.img = self.compressImage(self.img)
        super(Post, self).save(*args, **kwargs)
    def get_comments(self):
        a = self.comments.all()
        if len(a) < 2:
            return list(a)
        else:
            return a
    @property
    def get_comments_length(self):
        x = list(self.comments.all())
        if x:
            return '{0} comments present, click to view.'.format(len(x))
        else:
            return 'No comments added, click to add comments'
    def get_tags(self):
        a = self.tag.all()
        if len(a) < 2:
            return list(a)
        else:
            return a



    def get_links(self):
        a = self.link.all()
        if len(a) < 2:
            return list(a)
        else:
            return a
    def get_user(self):
        if self.user is None:
            return 'Anonymous'
        if self.user.is_admin:
            return 'Admin'
        elif self.user.is_staff:
            return self.user.username
        else:
            return 'Anonymous'

    @property
    def posted_on(self):
        timezone = pytz.timezone('Asia/Kolkata')
        today = datetime.datetime.now(timezone)
        difference = today - pytz.utc.localize(self.date)
        difference = humanize.naturaldelta(difference)
        try:
            #x = '{0}  |  {1} '.format(self.user.username, self.date.strftime('%d %b %Y %I %M %p'))
            x = '{0}  |  {1} ago'.format(self.user.username, difference)

            return x
        except:
            return 'Group Admin'

aaa/notifications/models.py
from django.db import models
from accounts.models import User
from home.models import Post
import pytz, datetime
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
# Create your models here.





class Notification(models.Model):
    user = models.OneToOneField(User,on_delete= models.SET_NULL, null = True, blank = True)
    message = models.ManyToManyField('notifications.Message')
    count = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.user.email

class CustomManager(models.Manager):
    def delete_messages(self, url):
        x = super().get_queryset().filter(post_url = url)
        if x:
            x.delete()
        return True




class Message(models.Model):
    date = models.DateTimeField(auto_now_add=True,auto_now=False, null=True)
    text = models.CharField(blank=True,null=True, max_length=200)
    post_url = models.URLField(blank=True, null=True)
    type = models.CharField(blank=True,null=True, max_length=100)
    read = models.BooleanField(default=False, null = True)
    objects = CustomManager()
    def create_notifications(self, post_user):
        users = list(User.objects.filter(staff= True))
        for user in users:
            if user != post_user:
                try:
                    notification = user.notification
                    notification.count += 1
                    print(self)
                    notification.message.add(self)
                    notification.save()
                except ObjectDoesNotExist:
                    notification = Notification.objects.create(user = user, count = 0)
                    notification.count += 1
                    print(self)
                    notification.message.add(self)
                    notification.save()
        return 'hello'

aaa/home/forms.py
from django.forms import ModelForm
from django import forms
from .models import Post, Tag, Comment


class Custommmf(forms.ModelMultipleChoiceField):
    def label_from_instance(self, tag):
        return  '%s' % tag.name

class CreatePostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['tag','heading', 'img', 'content', 'pdf_name', 'pdf']

    tag = Custommmf(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )
    
    def __init__(self, *args, **kwargs):
        super(CreatePostForm, self).__init__(*args, **kwargs)
        self.fields['heading'].widget.attrs['placeholder'] = 'Post heading/Question/title'
        self.fields['tag'].required = True
        self.fields['pdf_name'].widget.attrs['placeholder'] = 'name of pdf'
        self.fields['content'].widget = forms.Textarea(attrs={'rows': 4, 'cols': 15})
        self.fields['content'].widget.attrs['placeholder'] = 'Content of post/mcq/answer'

aaa/notifications/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import Notification
from home.models import Tag
from django.utils.decorators import method_decorator
from home.decorators import staff_required
# Create your views here.


@method_decorator(staff_required, name = 'dispatch')
class ShowNotification(TemplateView):
    template_name = 'home/notifications.html'
    def get(self, request, *args, **kwargs):
        try:
            notif = Notification.objects.get(user=self.request.user)
        except Exception as e:
            notif = Notification.objects.create(user = self.request.user, count = 0)
        self.kwargs['count'] = notif.count
        notif.count = 0
        notif.save()

        return super().get(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag_speciality = Tag.objects.filter(is_speciality=True)
        messages = list(self.request.user.notification.message.all())
        context['tag_speciality'] = list(tag_speciality)
        messages.reverse()
        context['new_notifications'] = messages[0:self.kwargs['count']]
        context['notifications'] = messages[self.kwargs['count']:]
        print(context)
        return context

aaa/home/templates/home/getposts.html
{% if post %}
{% load static %}





<div class="flex-column">
  <div class="flex-row" style="justify-content: space-between">
    <p style="color: #000066"><b>{{post.posted_on}}</b> </p>
    <div class="socialmediatags tags">

      <a href="https://api.whatsapp.com/send?text={{ post.get_absolute_url }}" data-action="share/whatsapp/share"><img src="{% static 'home/images/whatsapp.png' %}" height=20px, width=20px alt=""> </a>
<a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={{ post.get_absolute_url }}" ><img src="{% static 'home/images/facebook.png' %}" height=20px, width=20px alt=""></a>
<a  onclick="navigator.clipboard.writeText('{{ post.get_absolute_url }}'); alert('link: {{ post.get_absolute_url }} ')"><img src="{% static 'home/images/copy.png' %}" height=20px, width=20px alt=""></a>


    </div>
  </div>


    <div class="regulartags tags">
      {% for tag in post.get_tags %}
      {% if tag.is_degree %}
      <p class="degree"><a style="margin:5px;text-decoration:none;color: white;" href="{% url 'home:speciality' tag.name %}">{{tag.name}}</a></p>
      {% else %}
      {% if tag.name == 'Conferences' %}

      <p style="text-decoration:none; font-weight: 400;margin-right: 10px;text-align: center;" ><a id = '{{tag.name}}' style="margin: 5px;text-decoration: none" href="{% url 'home:conf' %}">{{tag.name}} </a>  </p>

      {% else %}
      <p style="text-decoration:none; font-weight: 400;margin-right: 10px;text-align: center;" ><a id = '{{tag.name}}' style="margin: 5px;text-decoration: none" href="{% url 'home:speciality' tag.name %}">{{tag.name}} </a>  </p>

      {% endif %}
      {% endif %}
      {% endfor %}
    </div>


</div>

{% if request.user.is_authenticated and request.user == post.user or request.user.is_admin%}
<form onsubmit="deleteposte(event, {{post.pk}})" method="post" enctype="application/x-www-form-urlencoded">
{% csrf_token %}
<input type="submit" name = 'deletepostbtn{{post.pk}}' value="Delete Post" style="text-decoration: underline; color: white; background-color: #800000;" >
</form>
{%endif %}
<div class="home-post-heading">
    <h3>{{post.heading | linebreaks }}</h3>


</div>


{% if post.img %}
<div class="home-post-img">
    <img  src="/media/{{post.img}}" width="250px" height="250px">
</div>

{% endif  %}


{% if post.content %}
<div class="home-post-content">
    <p>{{post.content|linebreaks }}</p>
</div>
{% endif  %}


{% if post.get_links %}
{% for i in post.get_links %}
<div class="home-post-link">
    <a href="{{i.link}}"><p>{{i.link_name}}: {{ i.link }}</p></a>
</div>
{%endfor%}
{% endif  %}

{% if post.pdf %}
<b>Attached Pdfs</b>
<div class="home-post-pdf">
    <a href="/media/{{post.pdf}}">{{post.pdf_name}} /media/{{post.pdf}}</a>
</div>
{% endif  %}
<nav onclick="showcommentsdh('comments{{ post.pk  }}')" style="display: flex; justify-content: flex-start; height: auto; color: white;">
  {% if request.user.is_authenticated and request.user.is_staff %}
  <a >{{ post.get_comments_length }}</a>
  {% elif request.user.is_authenticated and request.user.is_staff == False %}
  <a>You have visitor privileges and need to be approved by Admin to interact in the website.</a>

  {% else %}
  <a href="{% url 'accounts:login' %}">Login to see/post comments</a>
  {% endif %}

</nav>
{% if request.user.is_staff %}
<div id="comments{{post.pk}}" class="comments ">

{% if post.get_comments %}
<div class="home-post-comments">
{% for comment in post.get_comments %}
    <div class="home-post-comment-single">
        <div class="flex-row end-end">
          <p style="font-size: 14px;text-decoration:underline;color: #000066"><b>{{comment.user.username}} | {{comment.posted_on}}  </b>   </p>
          {% if request.user.is_staff and request.user == comment.user%}
          <p><a style="margin-right: 3px" onclick="deletecomment(event, {{comment.pk}})"><img src="{% static 'home/images/delete.png' %}" height="20px" width="20px" alt=""></a></p>
              {%endif %}
        </div>


  {% if comment.img %}

<div  class="home-post-img">
    <img  src="/media/{{comment.img}}" width="250px" height="250px">
</div>

{% endif  %}



{% if comment.text %}
<div class="home-post-content">
    <p>{{comment.text|linebreaks }}</p>
</div>
{% endif  %}




{% if comment.get_links %}
        <b>Attached links</b>
{% for i in comment.get_links %}
<div class="home-post-link">
    <a href="{{i.link}}"><p>{{i.link_name}}: {{i.link}}</p></a>
</div>
{%endfor%}
{% endif  %}
{% if comment.pdf %}
        <b>Attached pdfs</b>
<div class="home-post-pdf">
    <a href="{{comment.pdf}}"><p>{{comment.pdf_name}}: {{comment.pdf}}</p></a>
</div>
{% endif  %}
        </div>
{% endfor %}
</div>
{% endif  %}
{% if request.user.is_staff %}
<div class="comment-create-form">
 <form enctype="multipart/form-data" method="post" action="{% url 'home:commentform' post.pk %}">
        {% csrf_token %}
    <p><textarea required type="text" name="text" placeholder="Enter Comment.."></textarea></p>

    <button name="createcomment" type="submit" value="createcomment">Submit</button>
    </form>

    </div>
{% endif %}

</div>
{% endif %}
{% endif %}

aaa/home/templates/home/neet.html
{% extends 'home/base.html' %}
{% load static %}
{% block main %}

<style>
    .neet{
        display: flex;
        flex-flow: column wrap;

    }
    .subject-intro p{
      line-height: 25px;
      font-size: 18px;
    }

     @media screen and (max-width: 800px) {

     }
</style>

<div class="neet" >

    <h2 style="align-self:center; text-decoration: none;color: #000066; font-size: 20px; font-weight: 600;">
    NEET SUPER SPECIALITY.

</h2>
<a style="align-self: center" href="{% url 'home:postForm'  %}" ><p>Add a new post</p></a>
<div class="subject-intro" style=" font-family: 'Source Serif Pro', serif;">
        {% if tag.get_details %}
        {% for i in tag.get_details %}
        <div class="showsubjectintro">
        <h2 style="text-decoration: underline; font-weight: 600; color: #000066;">{{i.heading}}</h2>
            <script>
                var action{{i.pk}} = "{% url 'home:edittagdetail' tag.pk i.pk %}";
            </script>
            {% if request.user.is_authenticated and request.user.is_admin  %}
            <script>var deleteurl{{i.pk}} = '{% url "home:deletetagdetail" tag.pk i.pk %}'</script>
            <p><a style="text-decoration: underline; color: blue;" onclick="editsubjectintro(action{{i.pk}}, '{{ i.heading }}', '{{ i.details }}', '{{ i.pk }}') ">Edit</a> | <a style="text-decoration: underline; color: #000066" onclick="removebook(deleteurl{{i.pk}})">Remove detail </a></p>
            {% endif %}
        <p></p>
            {% if i.details %}
            <p>{{i.details|linebreaks }}</p>
            {% else %}
        <p><a style="text-decoration: underline; color: blue;" onclick="editsubjectintro(action{{i.pk}}, '{{i.heading}}', '{{i.details}}', '{{ i.pk }}')">Edit </a>| <a style="text-decoration: underline; color: #000066" onclick="removebook(deleteurl{{i.pk}})">Remove detail </a></p>
            {% endif %}
        </div>
        {% endfor %}
        {% endif %}
        {% if request.user and request.user  %}
        <p><a style="text-decoration: underline; color: blue;" onclick="addsubjectintro()">Add more details </a></p>
        {% endif %}
 <style>
                .subject-intro-edit textarea{
                    height: 300px; width: 80%;background-color: white;  font-size: 20px;  font-family: 'Source Serif Pro', serif;
                }
                #subject-intro-add textarea{
                    height: 300px; width: 80%;background-color: white;  font-size: 20px;  font-family: 'Source Serif Pro', serif;
                }
                #subject-intro-add input{
                        width:40%;
                }

                .subject-intro-edit input{
                        width: 40%;
                }
                @media screen and (max-width: 800px) {
                    #subject-intro-add textarea{
                        width: 100%;
                    }
                    #subject-intro-add input{
                        width:100%;
                    }
                    .subject-intro-edit textarea{
                        width: 100%;
                    }
                    .subject-intro-edit input{
                        width: 100%;
                    }
                }
            </style>
        {% if request.user.is_staff  %}
        <form style="display: none;" id = 'subject-intro-edit' class="subject-intro-edit" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p><input placeholder="Add heading.." style="border-radius: 4px;  height: 35px;  font-size: 14px;  font-family: 'Overlock', cursive;" required name="heading" type="text" maxlength="50" value="{{i.heading}}"></p> <br>
                <p><textarea placeholder="Add details.."  required name="details" type="text" maxlength="5000" >{{i.details}} </textarea></p>

                <button style="border-radius: 4px;  width:65px;  height:40px;  background-color: #000066; color: white;" name="edittagdetail" type="submit" value="profdetails">Submit</button>
            </form>

        <form style="display: none;" action="{% url 'home:addtagdetail' tag.pk %}" method="post" id="subject-intro-add" enctype="application/x-www-form-urlencoded">
             {% csrf_token %}

              <p><input placeholder="Add heading..." style="border-radius: 4px;  height: 35px;  font-size: 14px;  font-family: 'Overlock', cursive;" required name="heading" type="text" maxlength="50" value=""></p> <br>
                <p><textarea placeholder="Add details..." required name="details" type="text" maxlength="500" > </textarea></p>

                <button style="border-radius: 4px;  width:65px;  height:40px;  background-color: #000066; color: white;" name="addtagdetail" type="submit" value="profdetails">Submit</button>

         </form>
        {% endif %}
    </div>
    {% include "home/basetemplates/homecontainer.html" %}

</div>


{% endblock %}

aaa/home/templates/home/postdetail.html
{% extends "home/base.html" %}
{% load static %}
{% block main %}
{% include "home/basetemplates/homepost.html" %}
{% endblock %}